### ISSUE TITLE
from rflib import *  ImportError: No module named rflib

### ISSUE THREAD

**Issue by Odin979** [atlas0fd00m/rfcat#100]
Hello everyone,

I've been following these tutorials on how to set up and use rfcat with the yardstick one:
https://softwaretester.info/install-rfcat-on-kali-linux-2020-4/
http://console-cowboys.blogspot.com/2017/10/hacking-everything-with-rf-and-software_24.html

but I ran into an issue whenever I run the python code. Here is what I'm getting:
from rflib import * 
ImportError: No module named rflib

I'm a noob and not familiar with python, and I've looked on the internet and couldn't find a solution for that. All I want at this time is to be able to transmit a signal with yardstick one.

Thanks.

**Comment by Loumiakas** [comment]
Hello,

It looks like you have not installed rfcat library or it was not found inside your Python installation.

Firstly make sure that you are using Python3 as opposed to Python2. Python2 has reach end-of-life on 01/01/2021. 

Once you have Python3 installed, you will need to install rfcat library. Easiest and most straight forward way is doing it through python package manager (pip). Pip installation instructions can be found [here](https://pip.pypa.io/en/stable/installing/).

Once pip is available on your system, you can easily install python libraries. Instructions on how to install libraries can be found [here](https://pip.pypa.io/en/stable/user_guide/).

In your case, you would have install rfcat library with ```sudo python3 -m pip install rfcat``` or ```sudo pip3 install rfcat```.

Also, keep in mind that for some operating systems, you will need to invoke your python scripts with elevated privileges i.e. sudo, as some operating systems don't allow non-root access to the Yardstrick device.

**Comment by atlas0fd00m** [comment]
thank you, @Loumiakas .  that's a great intro.

@Odin979 if by chance you *do* happen to have RfCat installed, this error message could indicate that you've included white-space in your command (eg. if you copy/pasted that line in to python).  if you enter `import rflib` in interactive python, what does that give you?

**Comment by Odin979** [comment]
Thank you guys @Loumiakas @atlas0fd00m, 

It appears that the problem was with using python2 instead of 3. Once I've used python3, everything worked seamlessly.
