### ISSUE TITLE
Help needed with YS1 on raspberry pi 4

### ISSUE THREAD

**Issue by bking46** [atlas0fd00m/rfcat#101]
Hi All,
I am in dear need of help with the following issue I have encountered with rfcat on the raspberry pi with the yard stick one. My OS is Raspbian Buster, firmware rev on YS1 is 0348/x00 and bootloader is CC Bootloader

1.Executing print(d.reprRadioConfig()) in rfcat -r:
This outputs compiler not found, update needed.
Entered d.bootloader(), all leds on the ys1 lit up suggesting this is working. In addition I see the following line 
"RESETUP set from recv thread"
2. In a separate terminal window I navigate to the location where the firmware folder is saved and issue make installRfCatYS1CCBootloader however this outputs error please see attached picture
![20210207_175935](https://user-images.githubusercontent.com/58046919/107286363-29c7c380-6a69-11eb-85f6-e27ec304b3e8.jpg)
SDCC is v3.8.0. I don't know how to install 3.5.0 since this could not be found in the repository. 

Could you kindly help me get the ys1 to receive and transmit? Is the error I am getting due to the SDCC version? If yes, could you kindly guide me on how I can install the 3.5.0 version on Raspbian Buster ? What do I need to do to get rid of the "compiler not found, update needed message"?

Thank you for your help and patience!

**Comment by atlas0fd00m** [comment]
in the latest releases, there are firmware builds you can use to update your dongle.  i'm not sure how to get SDCC v3.5.0 on Raspbian.  i do my builds on Ubuntu, and i have to include older versions (bionic) to get SDCCv3.5.0.  i haven't figured out why yet, but >v3.5.0 creates firmware that don't work in any meaningful way.

if you download the firmware from the release (https://github.com/atlas0fd00m/rfcat/releases/download/v1.9.5/RfCatYS1CCBootloader-201231.hex), you should be able to update the firmware as follows:

```
$ rfcat --bootloader --force -S 
$ rfcat_bootloader /dev/RFCAT_BL_YS1 erase_all
$ rfcat_bootloader /dev/RFCAT_BL_YS1 download RfCatYS1CCBootloader-201231.hex
$ rfcat_bootloader /dev/RFCAT_BL_YS1 verify bins/RfCatYS1CCBootloader-201231.hex && rfcat_bootloader /dev/RFCAT_BL_YS1 run
```

i hope this helps :)
@

**Comment by bking46** [comment]
> in the latest releases, there are firmware builds you can use to update your dongle. i'm not sure how to get SDCC v3.5.0 on Raspbian. i do my builds on Ubuntu, and i have to include older versions (bionic) to get SDCCv3.5.0. i haven't figured out why yet, but >v3.5.0 creates firmware that don't work in any meaningful way.
> 
> if you download the firmware from the release (https://github.com/atlas0fd00m/rfcat/releases/download/v1.9.5/RfCatYS1CCBootloader-201231.hex), you should be able to update the firmware as follows:
> 
> ```
> $ rfcat --bootloader --force -S 
> $ rfcat_bootloader /dev/RFCAT_BL_YS1 erase_all
> $ rfcat_bootloader /dev/RFCAT_BL_YS1 download RfCatYS1CCBootloader-201231.hex
> $ rfcat_bootloader /dev/RFCAT_BL_YS1 verify bins/RfCatYS1CCBootloader-201231.hex && rfcat_bootloader /dev/RFCAT_BL_YS1 run
> ```
> 
> i hope this helps :)
> @

Thank you so much for the quick answer. As I understood from your message, I can get away without having to install SDCC v3.5.0 instead I just run the commands you mentioned after bootloader force is initiated - have I understood correctly? After I complete these steps will print(d.reprRadioConfig()) show the compiler version? Thanks

**Comment by atlas0fd00m** [comment]
correct.

**Comment by bking46** [comment]
Thanks again for your help, have run the above commands however "rfcat_bootloader /dev/RFCAT_BL_YS1 verify bins/RfCatYS1CCBootloader-201231.hex && rfcat_bootloader /dev/RFCAT_BL_YS1 run" is thowing out the following error:
![20210209_103502](https://user-images.githubusercontent.com/58046919/107339480-66290d00-6ac5-11eb-9392-40366c6bda2e.jpg)

I skipped the verify portion and did "rfcat_bootloader /dev/RFCAT_BL_YS1 run". I can now see the new firmware:
![20210209_104210](https://user-images.githubusercontent.com/58046919/107339167-0af71a80-6ac5-11eb-9080-8ec917e8ffcf.jpg)

The issues I still have rx and tx still don't work:
Rx:
![20210209_104143](https://user-images.githubusercontent.com/58046919/107339289-2feb8d80-6ac5-11eb-83eb-10d63b4fe7a0.jpg)
Tx:
![20210209_104128](https://user-images.githubusercontent.com/58046919/107339330-3f6ad680-6ac5-11eb-8602-c3fb6564d608.jpg)

Any suggestions on how to have this fixed? Also is there a way to uninstall rfcat from the raspberry and start with a new install?

Thanks for your help and patience

**Comment by atlas0fd00m** [comment]
glad it helped.

i apologize, i apparently failed to copy/paste well, and added in the "bin/" part to the filename.  thankfully, just for the verify part.

as for transmit:
this is now Python3:
```
d.RFxmit(b'HALLO') 
```

d.RFrecv() *does* throw a TimeoutException if a packet doesn't arrive within the timeout time.
are you sure this is an error?  or just an actual timeout?

i should really do something about that ChipconUsbTimeoutException.... there's currently not a pretty way to make it something else, but that's the normal error if timeout occurs while waiting for a packet.

**Comment by bking46** [comment]
Thanks for all your support and guidance with this, much appreciated!

I keep forgetting that a lot of code is now using the python3, adapting the command works as expected. For the Rx I will need to do some further testing with an SDR or try to use the rfcat -s to be sure I was tunned to the correct frequency and check the Rx.

Again thanks for the help!

**Comment by bigoper** [comment]
# 01 bking46 is KING
@bking46 
You are the KING!
Following your steps saved me :)
Thank you!

# 02 SDCC 3.5.0
- Download the source from [here](http://ftp.de.debian.org/debian/pool/main/s/sdcc/)
- How to build it [here](https://edisciplinas.usp.br/pluginfile.php/5813811/mod_resource/content/1/sdccman.pdf)

# 03 Enable bootloader mode when the firmware isn’t running
- The bootloader mode on the YARD Stick One can be triggered by connecting pins 7 and 9 on the P1 expansion header.
- Link [here](https://roaldnefs.com/posts/2019/01/update-yard-stick-one-firmware/)
