### ISSUE TITLE
YARD Stick One doesnt send anything :(

### ISSUE THREAD

**Issue by YallTrippin** [atlas0fd00m/rfcat#102]
Hello.....
could anybody tell me how to fix this issue please?
logs down below

`not-root@who-knows:~ $ rfcat -r
'RfCat, the greatest thing since Frequency Hopping!'

Research Mode: enjoy the raw power of rflib

currently your environment has an object called "d" for dongle.  this is how 
you interact with the rfcat dongle:
    >>> d.ping()
    >>> d.setFreq(433000000)
    >>> d.setMdmModulation(MOD_ASK_OOK)
    >>> d.makePktFLEN(250)
    >>> d.RFxmit("HALLO")
    >>> d.RFrecv()
    >>> print(d.reprRadioConfig())

2021-02-20 11:20:10,029:DEBUG:asyncio: Using selector: EpollSelector

2021-02-20 11:20:10,944:DEBUG:asyncio: Using selector: EpollSelector
In [1]: d.RFxmit("HALLO")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/rfcat-1.9.5-py3.7.egg/rflib/__init__.py in <module>
----> 1 d.RFxmit("HALLO")

/usr/local/lib/python3.7/dist-packages/rfcat-1.9.5-py3.7.egg/rflib/chipcon_nic.py in RFxmit(self, data, repeat, offset)
   1125         waitlen += repeat * (len(data) - offset)
   1126         wait = USB_TX_WAIT * ((old_div(waitlen, RF_MAX_TX_BLOCK)) + 1)
-> 1127         self.send(APP_NIC, NIC_XMIT, b"%s" % struct.pack("<HHH",len(data),repeat,offset)+data, wait=wait)
   1128 
   1129     def RFxmitLong(self, data, doencoding=True):

TypeError: can't concat str to bytes

In [2]: quit
===== RESETUP set from recv thread
Speicherzugriffsfehler
`

Not being able to send some shit is one thing, but what the hack means the gibberish it spit out
after i typed `quit`?

Thanks for answering and best regards!

**Comment by atlas0fd00m** [comment]
hey @YallTrippin ,
you need to add a "b" to the front of HALLO:
`d.RFxmit(b"HALLO")`

as for the end, the "RESETUP" comment is about RfCat attempting to re-establish communication with the dongle.

**Comment by YallTrippin** [comment]
@atlas0fd00m 
nope, sorry......doesnt seem to work for me with the b in front :(
as usual, logs below

`$ rfcat -r
'RfCat, the greatest thing since Frequency Hopping!'

Research Mode: enjoy the raw power of rflib

currently your environment has an object called "d" for dongle.  this is how 
you interact with the rfcat dongle:
    >>> d.ping()
    >>> d.setFreq(433000000)
    >>> d.setMdmModulation(MOD_ASK_OOK)
    >>> d.makePktFLEN(250)
    >>> d.RFxmit("HALLO")
    >>> d.RFrecv()
    >>> print(d.reprRadioConfig())


2021-02-22 15:28:07,886:DEBUG:asyncio: Using selector: EpollSelector
^[[A
2021-02-22 15:28:08,752:DEBUG:asyncio: Using selector: EpollSelector
In [1]: d.RFxmit(b"HALLO")
---------------------------------------------------------------------------
ChipconUsbTimeoutException                Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/rfcat-1.9.5-py3.7.egg/rflib/__init__.py in <module>
----> 1 d.RFxmit(b"HALLO")

/usr/local/lib/python3.7/dist-packages/rfcat-1.9.5-py3.7.egg/rflib/chipcon_nic.py in RFxmit(self, data, repeat, offset)
   1125         waitlen += repeat * (len(data) - offset)
   1126         wait = USB_TX_WAIT * ((old_div(waitlen, RF_MAX_TX_BLOCK)) + 1)
-> 1127         self.send(APP_NIC, NIC_XMIT, b"%s" % struct.pack("<HHH",len(data),repeat,offset)+data, wait=wait)
   1128 
   1129     def RFxmitLong(self, data, doencoding=True):

/usr/local/lib/python3.7/dist-packages/rfcat-1.9.5-py3.7.egg/rflib/chipcon_usb.py in send(self, app, cmd, buf, wait)
    614         if self._debug: print("Sent Msg %s" %\
    615                 hexlify(msg))
--> 616         return self.recv(app, cmd, wait)
    617 
    618     def reprDebugCodes(self, timeout=100):

/usr/local/lib/python3.7/dist-packages/rfcat-1.9.5-py3.7.egg/rflib/chipcon_usb.py in recv(self, app, cmd, wait)
    577                 sys.excepthook(*sys.exc_info())
    578 
--> 579         raise ChipconUsbTimeoutException
    580 
    581     def recvAll(self, app, cmd=None):

ChipconUsbTimeoutException: Timeout waiting for USB response.

`

**Comment by YallTrippin** [comment]
EDIT:
@atlas0fd00m 
but if i execute rfcat -r with sudo in front it works 🗡️ 
Thank you!

**Comment by atlas0fd00m** [comment]
:)
