### ISSUE TITLE
error in resetup while flashing bootloader. currently running python2.7 and sdcc3.5

### ISSUE THREAD

**Issue by lazyjay559** [atlas0fd00m/rfcat#104]
so I installed pyenv to get my system running on python2.7. I've got SDCC3.5 installed. All dependencies are there. I'm not sure what is going on now as the flashing keeps failing. 

[~/rfcat/firmware]
└─# make installRfCatYS1CCBootloader
==RfCatYS1CCBootloader.hex building==
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` --xram-loc 0xF000  --code-loc 0x1400 appFHSSNIC.c chipcon_usb.rel chipcon_usbdebug.rel chipcon_dma.rel bootloader.rel cc1111rf.rel global.rel cc1111_aes.rel -DYARDSTICKONE -DCC1111 -DUSBDEVICE
packihx <appFHSSNIC.ihx >bins/RfCatYS1CCBootloader.hex
packihx: read 622 lines, wrote 1199: OK.
if [ ! -c /dev/RFCAT_BL_YS1 ] ; then ../rfcat --bootloader --force -S && sleep 1 ; fi ;
Entering RfCat Bootloader mode, ready for new image...
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)

...it just times out but stays in bootloader mode, the lights are still on 
here's my config...

In [1]: print(d.reprRadioConfig())
== Hardware ==
Dongle:              YARDSTICKONE
Firmware rev:        0348
Compiler:            Not found! Update needed!
Bootloader:          CC-Bootloader

== Software ==
rflib rev:           615

== Frequency Configuration ==
Frequency:           901999877.929688 hz (0x259555)
Channel:             0
Intermediate freq:   281250 hz
Frequency Offset:    0 +/-
Est. Freq Offset:    22

== Modem Configuration ==
Modulation:          2FSK
DRate:               38360.595703 hz
ChanBW:              93750.000000 hz
DEVIATION:           20507.812500 hz
Sync Mode:           15 of 16 bits must match
Min TX Preamble:     4 bytes
Chan Spacing:        199951.171875 hz
BSLimit:             No data rate offset compensation performed
DC Filter:           enabled
Manchester Encoding: disabled
Fwd Err Correct:     disabled

== Packet Configuration ==
Sync Word:           0x0C4E
Packet Length:       255
Length Config:       Fixed Packet Mode
Configured Address:  0x0
Preamble Quality Threshold: 4 * 2
Append Status:       No
Rcvd Packet Check:   No address check
Data Whitening:      off
Packet Format:       Normal mode
CRC:                 disabled

== AES Crypto Configuration ==
AES Mode:            CBC - Cipher Block Chaining
Crypt RF Input:      off
Crypt RF Output:     off

== Radio Test Signal Configuration ==
TEST2:               0x88
TEST1:               0x31
TEST0:               0x9
VCO_SEL_CAL_EN:      0x0

== Radio State ==
     MARCSTATE:      MARC_STATE_RX (d)
     DONGLE RESPONDING:  mode :c, last error# 1

== Client State ==
========================================================================================================================
     client thread cycles:      49/14
     client errored cycles:     0
     recv_queue:                (0 bytes) ''
     trash:                     (3 blobs) "[128, 142, (1615477608.850434, '')]"
     recv_mbox                  (2 keys)  "['0x42', '0xff']"
       app 0x42 (1 records)
             [0x7]    (0 frames)  "[]"

       app 0xff (4 records)
             [0x88]    (0 frames)  "[]"
             [0x80]    (0 frames)  "[]"
             [0x82]    (0 frames)  "[]"
             [0x86]    (0 frames)  "[]"

It says compiler needed, which i currently have as SDCC3.5
# sdcc -v                                                                                                   127 ⨯
SDCC : mcs51/z80/z180/r2k/r3ka/gbz80/tlcs90/ds390/pic16/pic14/TININative/ds400/hc08/s08/stm8 3.5.0 #9253 (Jun 20 2015) (Linux)
published under GNU General Public License (GPL)

# python --version             
Python 2.7.18

I'm stuck here. I tried many work arounds until I got to this point with pyenv and thought everything was golden. Any ideas? Thank you in advance.

**Comment by atlas0fd00m** [comment]
```
$ rfcat --bootloader --force -S
$ ls /dev/RF*
```

**Comment by lazyjay559** [comment]
i can get to the bootloader either way, with rfcat -r or rfcat--bootloader --force, but it errors out when loading the new image with rfcat -r. How can I add the image manually after it's in bootlader mode with rfcat --bootloader --force -S? I don't have a problem getting it to bootloader mode, i have a problem flashing the new image. I don't have anything RFcat related in /dev/ either. not sure what you meant by that last command.Thank you for getting back to me so quick! You are awesome and I truly do appreciate all your effort you put in everyday.

**Comment by atlas0fd00m** [comment]
please show me the results of the ls command.
putting the dongle into bootloader mode *should* make /dev/RFCAT_YS1 appear.

if you're putting it into bootloader mode manually, how are you trying to download the firmware to the dongle?

if you are compiling custom firmware... don't put the dongle in bootloader mode.  the Makefile script does that for you.  

let me know if that changes anything.

**Comment by lazyjay559** [comment]
thanks! I had a typo when setting the udev rules and it didnt write I apparently wasn't paying attention that it failed. whoops... i moved it to /etc and ran make installRfCatYS1CCBootloader and it loaded as it should.
