### ISSUE TITLE
error running rfcat 

### ISSUE THREAD

**Issue by chinemys** [atlas0fd00m/rfcat#106]
I get this error, what can it depend on?

(root💀kali)-[/home/chine/rfcat]
└─# rfcat -h                                                             1 ⨯
Traceback (most recent call last):
  File "/usr/local/bin/rfcat", line 11, in <module>
    from rflib import *
  File "/usr/local/lib/python2.7/dist-packages/rflib/__init__.py", line 6, in <module>
    from builtins import str
ImportError: No module named builtins

**Comment by pickeditmate** [comment]
Try 
sudo rfcat -r
Then
help(d)

**Comment by chinemys** [comment]
thanks i solved, i had to enter the rules. i tried on termux (android) installing kali, but i always get errors running .with nethunter instead it works fine rfcat, but i can't run rfcrack.  ) .
i would run rfcat and rfcrack on rootfs (android) .
I'm going crazy to find the method, at the time I was successful with Linux deploy but now it has become paid, with termux very difficult.
If anyone kindly has a solution, I would be really grateful.
(I solved with nethunter, now I can use rfcat + rfcrack with python3).

**Comment by woutvanderploeg** [comment]
> Try
> sudo rfcat -r
> Then
> help(d)

But then i can't make my own python script with rflib because i get the error: 

```
from rflib import *
File "build/bdist.linux-x86_64/egg/rflib/__init__.py", line 6, in <module>
ImportError: No module named builtins
```

so how do i fix that

**Comment by woutvanderploeg** [comment]
If I run it in virtualenv it works just fine so I think I messed something up in the installation. Thanks for your reply :)

**Comment by atlas0fd00m** [comment]
:)
want to help.
let us know if you figure it out or need help.
