### ISSUE TITLE
Rfcat install Kali 2021

### ISSUE THREAD

**Issue by kevtheskin** [atlas0fd00m/rfcat#109]
Hello there, Can someone tell me if there is an updated install tutorial for just Rfcat. I had to re-install my practice kali box(just learning) and now Rfcat does not work. I followed this https://github.com/atlas0fd00m/rfcat#installing-client .

Thanks just an old Noobie keeping my brain working. Cheers 73s Kev

**Comment by atlas0fd00m** [comment]
in the past Kali has included a version of RfCat that didn't work well.

your best bet is to install RfCat from Pypi.
`$ python3 -m pip install rfcat`

**Comment by atlas0fd00m** [comment]
sorry, i won't close this until you let us know it worked.

**Comment by kevtheskin** [comment]
> python3 -m pip install rfcat

Hello Atlas , Thank you for your time . I did what you quoted and it looks like its installed (Requirement already satisfied: rfcat in /usr/lib/python3/dist-packages (1.0.1)  . Its still does not work. Also Rfcrack does not work either. Why does things have to be update  :) Thanks again for trying to help me . 73s Kev

**Comment by atlas0fd00m** [comment]
what's going on that's causing the failure?
what are the signs of failure?

**Comment by kevtheskin** [comment]
> what's going on that's causing the failure?
> what are the signs of failure?

Your asking me hahahahaha. 
Traceback (most recent call last):
  File "/usr/local/bin/rfcat", line 11, in <module>
    from rflib import *
  File "/usr/local/lib/python2.7/dist-packages/rflib/__init__.py", line 6, in <module>
    from builtins import str
ImportError: No module named builtins
Linux kali 5.10.0-kali7-amd64 #1 SMP Debian 5.10.28-1kali1 (2021-04-12) x86_64 GNU/Linux

This is the latest error?

**Comment by atlas0fd00m** [comment]
that's a messy error.
have you tried installing and running it on another system?

@

**Comment by pickeditmate** [comment]
Kev, I've just uninstalled and reinstalled from source and it's working great on Kali on the pi. 

My steps were to remove old traces from my previous install
sudo pip uninstall rfcat
sudo pip3 uninstall rfcat
find and remove any bins from rfcat if there are any in /use/local/lib/python... /rfcat
sudo git clone https://github.com/atlas0fd00m/rfcat
sudo python3 setup.py install

**Comment by meeas** [comment]
Before doing the commands @pickeditmate suggests, do a `sudo apt purge rfcat` to get rid of the Kali version.  Trun the list of commands @pickeditmate lists.

@atlas0fd00m was being kind when he said the Kali version didn't work well.  It has been 100% broken for 2 years in Kali because they tried to convert it from Python 2 to Python 3 and didn't bother doing any tests to verify their changes work.  They change lets you start `rfcat -r` without error, but fails when you try running any commands.

**Comment by atlas0fd00m** [comment]
cleaning up
