### ISSUE TITLE
Suggestion: Change the default frequency to 433.92 Mhz

### ISSUE THREAD

**Issue by meeas** [atlas0fd00m/rfcat#112]
@atlas0fd00m , what do you think about changing the rfcat firmware to default to 433.92 Mhz instead of 902 Mhz?  That puts the device in the middle of a frequency range that is legal to use for most countries around the world, helping rfcat users from accidental usage in illegal frequencies.  Of the available CC1111 ranges, that seems to make the most sense for an international audience.

**Comment by atlas0fd00m** [comment]
@meeas make a PR and i'll accept it.  your logic makes sense to me.

**Comment by atlas0fd00m** [comment]
cleaning up
