### ISSUE TITLE
Should  udev group for non-root access be changed to plugdev

### ISSUE THREAD

**Issue by rlourette** [atlas0fd00m/rfcat#114]
I recently installed a new Ubuntu 20.04 VM and followed the rfcat installation procedures. By default, I was not part of the 'dialout' group so the instructions to run these commands did not allow me to use rfcat without sudo.
```
sudo cp etc/udev/rules.d/20-rfcat.rules /etc/udev/rules.d
sudo udevadm control --reload-rules
```
Running the 'groups' command listed me as being a part of 'plugdev'. I have seen other examples showing 'plugdev' as the group to add the device to. Perhaps alternate udev rules should be added or the instructions could prompt the user to check which group they are a part of and to use the appropriate rules. I am not an expert, but I wanted to post an issue so that someone else with the issue can see what I did to resolve it. Below are the lines I used to solve the issue for me. Thank for maintaining this repo!. --Rich

```
# modern RfCats
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="6047", MODE:="0660", SYMLINK+="RFCAT%n", GROUP="plugdev"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="6048", MODE:="0660", SYMLINK+="RFCAT%n", GROUP="plugdev"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="605b", MODE:="0660", SYMLINK+="RFCAT%n", GROUP="plugdev"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="ecc1", MODE:="0660", SYMLINK+="RFCAT%n", GROUP="plugdev"
```

**Comment by atlas0fd00m** [comment]
added comment to README.md.  thanks for the comment, @rlourette !
