### ISSUE TITLE
Pyhon 3 bytes vs str bug in bits.py

### ISSUE THREAD

**Issue by theepicsnail** [atlas0fd00m/rfcat#115]
https://github.com/atlas0fd00m/rfcat/blob/e0583f879236282b6b1f508a597b1dc20c6194c0/rflib/bits.py#L164 and
 https://github.com/atlas0fd00m/rfcat/blob/e0583f879236282b6b1f508a597b1dc20c6194c0/rflib/bits.py#L166

```
/usr/local/lib/python3.8/dist-packages/rfcat-1.9.5-py3.8.egg/rflib/bits.py in findSyncWord(byts, sensitivity, minpreamble)
    162         while True:         # keep searching through string until we don't find any more preamble bits to pick on
    163             sbyts = byts
--> 164             pidx = byts.find("\xaa"*minpreamble)
    165             if pidx == -1:
    166                 pidx = byts.find("\x55"*minpreamble)

TypeError: argument should be integer or bytes-like object, not 'str'
```

**Comment by atlas0fd00m** [comment]
wow, rfbits has really suffered bitrot with py3 transition.
thanks for bringing this up.  i'm afraid i'm a bit behind on looking at issues, and this has been going on for a long time.

**Comment by atlas0fd00m** [comment]
PR's are always welcome :)

**Comment by atlas0fd00m** [comment]
check out the latest in master.
