### ISSUE TITLE
YS1 Dongle Not Found

### ISSUE THREAD

**Issue by cw7664** [atlas0fd00m/rfcat#118]
Hey there,

**NOTE** I have copy and pasted this from the Great Scott issues page (see [here](https://github.com/greatscottgadgets/yardstick/issues/20#issue-1122325001)) and reposting it here in case it is more apt here and to link them.

I cannot get my YS1 to work on Windows 11 or my Ubuntu 20.04 VM (VirtualBox). I have tried following all the documentation on here and the rfcat repository and every forum I could find.

Windows gives me some generic "Device not recognized/damaged" error message and just doesn't show up at all in Ubuntu. I got it to appear on Windows as a COM port when put it into bootloader mode by shorting pins 7 and 9 (all 3 LEDs did light up). However, I was still not able to do anything with it.

Back in Ubuntu I tried reloading firmware onto the device following this using both the methods described and had no luck. It kept giving me the "Dongle not found" error message when using "$ rfcat -r" or a message along the lines of "Device being used by something else like a manager." Sorry, I am not at my workbench to give you exact messages. But I have tried unplugging and replugging it dozens of times and nothing.

Next, I tried to downgrade my SDCC version from 3.8.0 to 3.5.0, but it could not be found in the repository.

Then tried installing the libusb-32 drivers using Zadig (along with the other drivers) with and without it in bootloader mode. No cigar.

I have scoured the internet and tried everything I could find on here and other forums with no success. I don't know if it is not compatible with my updated setup or what.

Thanks in advance.

**Comment by atlas0fd00m** [comment]
you may have uploaded bad firmware to your YS1 by using SDCC 3.8.0.  however, thanks for @argilo 's recent PR, i think you may be able to use modern SDCC's again to compile new firmware.

however, if you're already having issues, i recommend you use the firmware downloaded from one of the github releases and try on a computer running Ubuntu native (not in a VM) to make sure the hardware works ok before trying to figure out Windows and VirtualBox issues (which are their own pains)

@meeas or @cutaway may be able to help you figure out how to run it on Windows.  i gave up the Redmond beast 20+ years ago and have no desire to go back.  while i have appreciation for Win7 and i hear good things about Win10, no thank you.

**Comment by meeas** [comment]
All the YS1 come with a default firmware that is not compatible with Windows and require being flashed to a later firmware version.  It is so incompatible that VMware and VirtualBox can't even forward it properly.  So to flash it, you will need to be running Linux on hardware (not in a VM) and need SDCC 3.5.  I usually use the latest Ubuntu or Debian then pull the older SDCC package from an older repo.  No need to do anything with pins, the instructions should work to update the firmware.

Also be warned that unless I missed an update, the latest firmware loader flashes VERY slow so expect it to take a few minutes, but the plus side is the software works with Python3.

**Comment by atlas0fd00m** [comment]
@meeas , just got a patch to work around a bug in SDCC >3.5.0.  would love to hear your experience.  i haven't cut a new release yet, it's just fresh committed to mainline.

**Comment by meeas** [comment]
Awesome!  Thank you!  I will be happy to check it out.  I'm without a Yardstick right now, but I'll try it once I get home at the end of the week.

A quick question, I haven't looked into your make script, but how hard would it be to fork out the installer component so people can just install a binary without needing to compile?  I see a python script which may be stand alone already but I haven't poked at it yet.  Having a option in rfcat to download the latest binary (or include the binary with rfcat in pypi) and install would be a huge benefit for many of our users.  Something similar to how GSG implemented firmware updates with greatfet would be perfect.

A feature like that would also help with the current Yardstick issues.  GSG had tried to get the manufacturer to update the firmware on the last run but it seems it didn't happy.  If we can get a standalone installer for the binary, and then if we could also figure out why the install fails when running in a VM, then helping people get the YS updated will be much easier.

**Comment by atlas0fd00m** [comment]
thanks @meeas !  
the SDCC bug was just confirmed.  
i look forward to your experiences with compiling with the newer SDCC.

yes, RfCat can be flashed with pre-compiled firmware, which are included with most releases.
we don't have an auto-updater yet, but we're always accepting PRs!
i know you have the python skills, amigo :)

@

**Comment by argilo** [comment]
> Also be warned that unless I missed an update, the latest firmware loader flashes VERY slow so expect it to take a few minutes

I noticed that too. This should fix it: https://github.com/atlas0fd00m/rfcat/pull/125
