### ISSUE TITLE
No Dongle Found.

### ISSUE THREAD

**Issue by peseta3** [atlas0fd00m/rfcat#12]
Hallo all together,
I get this output, what can it be?
Sorry ,By the Yardstick One

`Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)`

And No, it is not that I have to plugin/out the dongle.

I want to make a firmware update

**Comment by peseta3** [comment]
Please Help with New Firmware Update.
I think somthing gone wrong, with my last.
The YS1 is not conected, I think.

**Comment by atlas0fd00m** [comment]
what's the output of lsusb?
did you unplug and replug?
are you somehow in "bootloader mode"?

**Comment by peseta3** [comment]
```
peseta3@peseta3-Lenovo-B50-50:~$ lsusb
Bus 001 Device 002: ID 8087:8001 Intel Corp. 
Bus 002 Device 002: ID 0bda:0129 Realtek Semiconductor Corp. 
Bus 002 Device 003: ID 05e3:0510 Genesys Logic, Inc. 
Bus 002 Device 004: ID 0bda:b728 Realtek Semiconductor Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
peseta3@peseta3-Lenovo-B50-50:~$ 

Yes I did unplug and replug.
I were in bootloader Mode before, but something goes wrong.
I can not go there  again.
```
now works fine

**Comment by atlas0fd00m** [comment]
let me know if you have further problems.  since it looks like this has resolved itself, i'll close this issue.  if i misunderstood and this is *not* resolved, please reopen and accept my apologies.

**Comment by glabmoris** [comment]
It may be worth mentioning that the "No Dongle Found. Please insert a RFCAT dongle" error is a recurrent issue with the YS1 and practically part of every experience with it, having to constantly unplug and replug the dongle (hundreds of times in the context of a RF experiment). 

Solving the underlying issue would be a tremendous increase in user experience. Is there an issue opened for this?

**Comment by peseta3** [comment]
Yes thank you, now ist all ok. In the moment i am ill, so I don´t work with that.

 

Von: atlas0fd00m [mailto:notifications@github.com] 
Gesendet: Donnerstag, 8. März 2018 21:42
An: atlas0fd00m/rfcat
Cc: peseta3; Author
Betreff: Re: [atlas0fd00m/rfcat] No Dongle Found. (#12)

 

let me know if you have further problems. since it looks like this has resolved itself, i'll close this issue. if i misunderstood and this is not resolved, please reopen and accept my apologies.

**Comment by atlas0fd00m** [comment]
@glabmoris i'm unaware of such a problem.  what versions of code are you using?  (what's on the YS1 and what version of the python library?)
what are you trying to do that causes this behavior?

**Comment by atlas0fd00m** [comment]
ahhh.  RfCat requires an RfCat-compatible dongle running the RfCat firmware.  to my knowledge, nobody has written any SDR-compatibility layer, so that message is expected.  please purchase an RfCat-compatible dongle (check the README).  if you want a recommendation, a YardStickOne from Great Scott Gadgets (cc: @mossmann) is probably the best dongle available.
