### ISSUE TITLE
Usage of dash-separated 'description-file' will not be supported in future versions

### ISSUE THREAD

**Issue by jonasstein** [atlas0fd00m/rfcat#120]
setuptools warnings detected:
Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead

https://github.com/atlas0fd00m/rfcat/blob/e0583f879236282b6b1f508a597b1dc20c6194c0/setup.cfg#L2

**Comment by atlas0fd00m** [comment]
thanks!  just merged in the change.
