### ISSUE TITLE
USB failure when using SDCC >= 3.8.0

### ISSUE THREAD

**Issue by argilo** [atlas0fd00m/rfcat#121]
I noticed that RfCat requires SDCC <= 3.5.0 (documented in #73 and enforced in 36f7727fa478044ac7d8787be0b65658de4e4f51). This is unfortunate since version 3.5.0 is almost 7 years old. Various users have reported that USB fails when RfCat is built with SDCC 3.8.0 or later. I decided to dig into this to see what the problem might be.

First, I bisected SDCC commits to see when the problem began, and tracked it down to https://sourceforge.net/p/sdcc/code/10263/, which went into the 3.8.0 release. Next I did some debugging and noticed that that failures were due to corruption of `ep5.OUTlen`, which causes various commands in `processOUTEP5` to transmit too much data. Adding the `volatile` keyword to the `USB_EP_IO_BUF` struct's `OUTlen` member makes the problem go away, but shouldn't be necessary because `OUTlen` is not written by any interrupt handlers.

It looks like SDCC miscompiles line 1014 of `chipcon_usb.c`:

```
;	chipcon_usb.c:1014: ep5.OUTlen += len;
	mov	a,_handleOUTEP5_len_1_175
	add	a,r7
	mov	r6,a
	mov	a,(_handleOUTEP5_len_1_175 + 1)
	addc	a,r6
	mov	r7,a
	mov	dptr,#(_ep5 + 0x0008)
	mov	a,r6
	movx	@dptr,a
	mov	a,r7
	inc	dptr
	movx	@dptr,a
```

Prior to this line, `r6` contains the MSB of `ep5.OUTlen` and `r7` contains the LSB of `ep5.OUTlen`. The first two instructions add the LSBs of `len` and `ep5.OUTlen`, but then the third instruction stores the sum in `r6`, overwriting the cached MSB of `ep5.OUTlen`. This then corrupts the sum of the MSBs, leaving a very large incorrect value in `ep5.OUTlen`.

Prior to https://sourceforge.net/p/sdcc/code/10263/, the roles of `r6` and `r7` are reversed, but the line is compiled correctly:
```
;	chipcon_usb.c:1014: ep5.OUTlen += len;
	mov	a,_handleOUTEP5_len_1_175
	add	a,r6
	mov	r6,a
	mov	a,(_handleOUTEP5_len_1_175 + 1)
	addc	a,r7
	mov	r7,a
	mov	dptr,#(_ep5 + 0x0008)
	mov	a,r6
	movx	@dptr,a
	mov	a,r7
	inc	dptr
	movx	@dptr,a
```

I did not spot any bugs in `handleOUTEP5`'s handling of `len` or `ep5.OUTlen`, which leads me to believe that this is a bug in SDCC.

RfCat could work around this by marking `OUTlen` as volatile, since this would prevent `ep5.OUTlen` from being cached in registers. But it seems like the underlying bug would need to be fixed in SDCC.

The problem remains in the latest release of SDCC (4.2.0, released 2022-03-08).

**Comment by atlas0fd00m** [comment]
@argilo , that is an excellent bit of binary-detective work!  thank you for that!  i've been unable to carve out the time to track this problem down, so we've been stuck using SDCCv3.5.0 for all these years.

would you be willing to make the change in your own fork and create a Pull Request?  if it makes SDCC function properly, i'm happy to make the change, but i'd like to be certain to have your name tagged to it, to give you proper credit.  if that's too much work, i'm happy to make the change and just make a comment about your finding the bug.  let me know.  i'd rather have you listed as a contributor tho. :)

thanks again!
@

**Comment by atlas0fd00m** [comment]
btw, also, i think you should bring this up to the SDCC compiler people, since you have done the detective work of tracking this one down.

**Comment by argilo** [comment]
> would you be willing to make the change in your own fork and create a Pull Request?

Sure, I'll open a pull request shortly.

**Comment by argilo** [comment]
I opened a bug report for the SDCC issue: https://sourceforge.net/p/sdcc/bugs/3381/

**Comment by argilo** [comment]
The SDCC folks have confirmed the bug. Once it's fixed, I'll add an `#ifdef` so the workaround is only applied when a broken compiler version is used.

**Comment by atlas0fd00m** [comment]
awesome, @argilo !  thank you :)
