### ISSUE TITLE
YS1 not found after Python exception

### ISSUE THREAD

**Issue by wimton** [atlas0fd00m/rfcat#126]
When an exception is thrown in a Python program, the error: "Error in resetup():USBTimeoutError(110, 'Operation timed out') appears on a subsequent invocation and the YS1 must be unplugged and reinserted.
OS: Recent Kali on 64-bit Intel. Using Python code, Git from 22-04-2022

**Comment by pickeditmate** [comment]
Did you issue a setmodeIDLE() at the end of your work? I get this a lot when using some script suites like rfcrack

**Comment by darconeous** [comment]
I'm noticing this, too, seems pretty annoying. Should be preventable.

**Comment by pickeditmate** [comment]
It IS preventable in code. 
The generally acceptable way in code is using exceptions and making sure you set the YS1 to idle after communication (and before configuring of course)

ConfigureD(d)

try:
    d.RFXmit(b'\xDE\xAD\xBE\xEF')
    d.setModeIDLE()
except Exception as e:
    time.sleep(3)
    ConfigureD(d)

**Comment by Crsarmv7l** [comment]
> Did you issue a setmodeIDLE() at the end of your work? I get this a lot when using some script suites like rfcrack

I noticed this as well, and fixed a bunch of his stuff.

**Comment by atlas0fd00m** [comment]
closing this valuable thread.  please reopen if there is benefit for it to be open.
