### ISSUE TITLE
make installys1bootloader fails

### ISSUE THREAD

**Issue by rlourette** [atlas0fd00m/rfcat#128]
`$ make installys1bootloader
./bootloader_serial.py
Traceback (most recent call last):
  File "./bootloader_serial.py", line 14, in <module>
    ser = int(file(".serial", 'rb').read(), 16) + 1
NameError: name 'file' is not defined
make: *** [Makefile:537: installys1bootloader] Error 1`

This occurs with:
Python 3.8.10

**Comment by atlas0fd00m** [comment]
thanks @rlourette !  that's embarrassing...

**Comment by atlas0fd00m** [comment]
updated.  please let me know if you run into other issues!

https://github.com/atlas0fd00m/rfcat/releases/tag/v1.9.6
https://pypi.org/project/rfcat/
