### ISSUE TITLE
TypeError when verifying firmware update

### ISSUE THREAD

**Issue by hunterking-google** [atlas0fd00m/rfcat#130]
$ make installRfCatDonsDongleCCBootloader 

==RfCatDonsCCBootloader.hex building==
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` --xram-loc 0xF000  --code-loc 0x1400 appFHSSNIC.c chipcon_usb.rel chipcon_usbdebug.rel chipcon_dma.rel bootloader.rel cc1111rf.rel global.rel cc1111_aes.rel -DDONSDONGLES -DCC1111 -DUSBDEVICE      
packihx <appFHSSNIC.ihx >bins/RfCatDonsCCBootloader.hex
packihx: read 620 lines, wrote 1193: OK.
if [ ! -c /dev/RFCAT_BL_D ] ; then ../rfcat --bootloader --force -S && sleep 1 ; fi ;
rfcat_bootloader /dev/RFCAT_BL_D erase_all
RC = 0(OK)
rfcat_bootloader /dev/RFCAT_BL_D download bins/RfCatDonsCCBootloader.hex
Writing :0614000002148B024B8E6A RC = 0(OK)
...(lots of writing output)
Writing :105A5000EC13FCEB13FBEA13FAE913F9D8F1227506 RC = 0(OK)

Writing :035A60008200229F RC = 0(OK)
Skipping non data record: ':00000001FF'
rfcat_bootloader /dev/RFCAT_BL_D verify bins/RfCatDonsCCBootloader.hex && rfcat_bootloader /dev/RFCAT_BL_D run
*** warning! this version of CC-Bootloader can only read 16 byte blocks!
*** upgrade recommended!
Verifying 0006 bytes at address: 1400Traceback (most recent call last):
  File "/home/blackbox/.local/bin/rfcat_bootloader", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/blackbox/rfcat-1.9.6/CC-Bootloader/rfcat_bootloader", line 236, in <module>
    verify_code(ihx_file, serial_port)
  File "/home/blackbox/rfcat-1.9.6/CC-Bootloader/rfcat_bootloader", line 67, in verify_code
    do_flash_read(serial_port, start_addr, block_length)
  File "/home/blackbox/rfcat-1.9.6/CC-Bootloader/rfcat_bootloader", line 134, in do_flash_read
    (0x100 - (length & 0xFF)) +
TypeError: unsupported operand type(s) for &: 'float' and 'int'
make: *** [Makefile:363: installRfCatDonsDongleCCBootloader] Error 1

**Comment by atlas0fd00m** [comment]
can you update (or use latest from git) and see if you still have this problem?

thanks!
@

**Comment by atlas0fd00m** [comment]
closing.  please reopen if this is still an issue.
