### ISSUE TITLE
Setting up rfcat in Debian 10 on Beaglebone black

### ISSUE THREAD

**Issue by bpayne7** [atlas0fd00m/rfcat#131]
hello, 

I am definitely new to Linux and rfcat, but I got rfcat to run on my window machine and ubuntu vm. Now I'm setting it up on a beaglebone black running Debian 10. I'm now getting error: pkg_resources.DistributionNotFound: The 'rfcat==1.9.6' distribution was not found and is required by the application

I've installed pyusb, libusb, ipython, pyreadline, etc. I've ran setup.py successfully. Any help would be greatly appreiciated!

Full output when running "sudo rfcat -r":

Traceback (most recent call last):
  File "/usr/bin/rfcat", line 4, in <module>
    __import__('pkg_resources').run_script('rfcat==1.9.6', 'rfcat')
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3259, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'rfcat==1.9.6' distribution was not found and is required by the application

**Comment by atlas0fd00m** [comment]
sorry, that's not making sense.  can you tell me where you got the `rfcat` code?

have you tried `pip install rfcat` ?

**Comment by bpayne7** [comment]
I cloned the `https://github.com/atlas0fd00m/rfcat.git` repository and ran `pip install rfcat` 

I can create a .py file and use rfcat from the file call, but I am getting the previous errors when running `sudo rfcat -r` in the terminal

I have been using python3, so maybe part of the issue with running rfcat directly on the terminal

**Comment by atlas0fd00m** [comment]
can you try it without sudo?
or possibly try `sudo pip install rfcat`

**Comment by bpayne7** [comment]
That worked...I think when I was running it before it was looking for version 1.9.6

reinstalling helped...now I can use the tool in the terminal and not just with .py files.

Thanks!

On Debian 10 Linux version 4.19.94

Ran `sudo pip3 install rfcat` -> Successfully installed rfcat-1.9.7

Ran `sudo rfcat -r` -> 'RfCat, the greatest thing since Frequency Hopping!'
