### ISSUE TITLE
Questions regarding calculatePKTChanBW and setEnableCCA

### ISSUE THREAD

**Issue by Crsarmv7l** [atlas0fd00m/rfcat#139]
I was digging through the RFlib here and found a couple very interesting functions, and I was wondering if they were accessible to the user, are they worth trying out, and are there any hardware risks if doing so.

The ones most interesting to me are RFcapture, calculatePKTChanBW and setEnableCCA.

setEnableCCA is probably the most interesting given the RSSI threshold filtering, but I was also hoping you might be able to provide examples of usage.

Thank you

**Comment by atlas0fd00m** [comment]
hey @Crsarmv7l !
yes, they are all accessible to the user.  yes, they're worth trying out.  no, they should not cause damage to the hardware.

**Comment by Crsarmv7l** [comment]
> hey @Crsarmv7l ! yes, they are all accessible to the user. yes, they're worth trying out. no, they should not cause damage to the hardware.

Thank you. I figured they were, but wanted to verify. I have been using while not keystop() already! Works great.

RFCapture looks self explanatory as does calculatePKTChanBW (which also looks like it sets the bandwidth after calculation).

Regarding setEnableCCA, I would like to set it to ignore below a certain RSSI, mode=1. Which I assume is d.setEnableCCA(mode=1) but where/how do I pass the RSSI params?

The function in question:
![Screenshot 2023-04-26 11 11 48 PM](https://user-images.githubusercontent.com/85343771/234889368-f380abde-8417-4c8c-b9b7-f715fcae5db6.png)

**Comment by atlas0fd00m** [comment]
did you figure it out?

best way to maximize your capability with RfCat is to get to know the cc1111 chip/radio.  search for cc1111-32.pdf (eg. https://www.ti.com/lit/ds/symlink/cc1110-cc1111.pdf)

setting the RSSI threshold has to do with the absthresh and relthresh and magn arguments.  look through the document for "rssi threshold" and you'll see at least how to set the Absolute Threshold.

let me know if you have any questions once you've done that.

hack fun!
@

**Comment by Crsarmv7l** [comment]
Thanks for the reference, and will do!

**Comment by Crsarmv7l** [comment]
> did you figure it out?
> 
> best way to maximize your capability with RfCat is to get to know the cc1111 chip/radio. search for cc1111-32.pdf (eg. https://www.ti.com/lit/ds/symlink/cc1110-cc1111.pdf)
> 
> setting the RSSI threshold has to do with the absthresh and relthresh and magn arguments. look through the document for "rssi threshold" and you'll see at least how to set the Absolute Threshold.
> 
> let me know if you have any questions once you've done that.
> 
> hack fun! @

Finally got back to this. Looked through the source and I believe I found what you were talking about....but I ended up implementing RSSI in software via rssi = d.getRSSI(), converting to an int and comparing it to a value. Seems to work pretty well but I realize at higher Drates it will be a bottleneck vice using the function which adjusts the registers and filters in hw.

One final question. How can you reset the dongle to the state it is in when plugged in. From the interactive shell, I see that it is MARC_STATE_RX, 13. I have tried d.RESET(), d.resetup, and a variety of the strobeMode's, but I am unsure what the 13 denotes and I am not sure any of them fully get it back to fresh plugged in state.
