### ISSUE TITLE
Simple Datarate question

### ISSUE THREAD

**Issue by Crsarmv7l** [atlas0fd00m/rfcat#143]
Somehow I have been able to do quite a lot without fully nailing this down...but a current project I am working on requires some precision rather than close then trial and error.

What unit does rfcat use for the datarate? Is it Baud=bits/s is it bytes/s 

Didn't see it in the readme.

**Comment by atlas0fd00m** [comment]
bits/s :)

**Comment by Crsarmv7l** [comment]
> bits/s :)

Awesome, that's what I expected. Thanks bud

**Comment by atlas0fd00m** [comment]
:)
