### ISSUE TITLE
PSK 

### ISSUE THREAD

**Issue by Crsarmv7l** [atlas0fd00m/rfcat#147]
Came across a very odd remote that uses BPSK at about 4800 baud.

I know PSK/BPSK is not technically supported on the CC1101/CC1111, but I came across this blog that shows it is kind of feasible by abusing MSK:
https://www.tablix.org/~avian/blog/archives/2016/06/ultra_narrowband_and_bpsk_on_ti_cc_chips/

Test results:
https://www.tablix.org/~avian/blog/archives/2016/06/bpsk_on_ti_cc_chips_2/

Would be a good feature to abstract and add for the very odd use case. Thoughts?

**Comment by Crsarmv7l** [comment]
Closing it was just an idea

**Comment by atlas0fd00m** [comment]
sorry, not a bad idea.  i'd be curious to see a pull request implementation :)

**Comment by Crsarmv7l** [comment]
Nah it's all good. I just closed because the datarates with such abuse would be low and maybe not very useful.

Sent you a couple pulls the other day. I'm working on something and have gone through nearly every function.

Once it's ready I would like to get your thoughts on it before putting it up on GitHub.

**Comment by atlas0fd00m** [comment]
sounds good.  yes, i see them now.  i've working through 700+ emails that have built up over the past couple weeks.

thank you for your efforts!
