### ISSUE TITLE
python3 port

### ISSUE THREAD

**Issue by aseemjakhar** [atlas0fd00m/rfcat#15]
Hi,

Im working on python port of expliot (https://bitbucket.org/aseemjakhar/expliot_framework, dumping the ruby version) and planning to implement rfcat plugins. Are you planning to port rfcat to python3?
I saw a discussion on bitbucket.org about it. Also, will you be uploading it to pypi as well?

Regards,
Aseem

**Comment by atlas0fd00m** [comment]
eventually, yes.  some of my primary tooling is porting to python3.  when that is done, rfcat is only a matter of time.  as for pypi, i'm 9/10ths of the way there.

@

**Comment by sundhaug92** [comment]
Is the plan to retain py2 compat after conversion?

**Comment by atlas0fd00m** [comment]
i would like that.  i haven't looked at what it would require yet, but i believe it'll not be too difficult.

**Comment by roaldnefs** [comment]
I would like to take a stab at porting the code to Python 3 while keeping compatible with Python 2, if @atlas0fd00m has not already started with porting the code to Python 3?

**Comment by atlas0fd00m** [comment]
that would be much appreciated!  i have not started yet.

**Comment by ZeroChaos-** [comment]
hey @atlas0fd00m , countdown is at 4 months, any chance of this getting more priority?

**Comment by atlas0fd00m** [comment]
@roaldnefs was working on this, and it's been a bit slow for the past few months.  i'm hoping he is interested in finishing the port. :)

thanks for bringing it up, @ZeroChaos-

**Comment by ZeroChaos-** [comment]
I also hope @roaldnefs is interested in finishing the port.  Let's hilight him a few more times and see if he is :-)

**Comment by roaldnefs** [comment]
Thanks for the reminder! I would like to finish the Python 3 port but currently very busy with other projects. Feel free to take over. I will give you an update if I can find some time to work on this.

**Comment by jonasstein** [comment]
Could you add some notes in the Todo file what has to be done for py3 support, please? That way contributors can check quickly where and how to help.

**Comment by roaldnefs** [comment]
I've created an overview of individual steps required for the Python 3 port in https://github.com/atlas0fd00m/rfcat/pull/40#issue-249820504.

**Comment by argilo** [comment]
Since the Python Foundation is nearly finished retiring Python 2 and distros are already starting to remove it, I don't think maintaining Python 2 compatibility is worth the extra effort. Anyone who wants to continue using Python 2 could just use an older version of rfcat.

**Comment by roaldnefs** [comment]
> Since the Python Foundation is nearly finished retiring Python 2 and distros are already starting to remove it, I don't think maintaining Python 2 compatibility is worth the extra effort. Anyone who wants to continue using Python 2 could just use an older version of rfcat.

I agree, but I am curious what the idea of @atlas0fd00m is?

**Comment by atlas0fd00m** [comment]
@roaldnefs how much effort would be required, and what kind of code-ugly do you estimate we're talking about to maintain 2.x compatibility?

i'm not one to restrict for restriction's sake.  i hate being forced away from Py2 myself, i don't want to be the driving force to Py3.  that said, if Py2 compatibility is going to make maintaining the code significantly worse or reduce the likelihood of success for a Py3 migration, those are compelling reasons to cut it.  if it's a few import statements and a minor approach difference to get both Py2 and Py3, and if @roaldnefs and the migration team are ok with it... i would far rather keep Py2-compat as long as it makes sense.

@

**Comment by argilo** [comment]
The main source of extra effort I had in mind was that anyone making changes (including during the porting effort) would have to test them in both Python 2 and Python 3. Since rfcat doesn't appear to have automated tests, I suspect this will be a significant cost, and that dispensing with Python 2 support would accelerate porting and future development. Just my 2¢.

**Comment by atlas0fd00m** [comment]
understood.  i had custom tests a while back but they include having two dongles and transmitting/receiving between them.  i'm open to PR's for unit tests for your favorite parts of rflib and dongle-comms.  however, in my experience it's not been incredibly hard to test most of the functionality of RfCat by simply getting into it and testing the code i just wrote.  if that turns into automated unittests code, i'm happy to incorporate that in.  

import unittest
there's already a stub included in the tests/ directory!

@

**Comment by atlas0fd00m** [comment]
i don't know if you noticed or not (i thought i had updated this forum), but i created a fake RfCat dongle class which basically emulates some of the functionality of the dongle, in order to unit-test the python library.

**Comment by roaldnefs** [comment]
> @roaldnefs how much effort would be required, and what kind of code-ugly do you estimate we're talking about to maintain 2.x compatibility?

As long as the used libraries support Python 2 this should be doable, otherwise we have to use old versions of those libraries or rewrite the logic for Python 2. [python-future.org](https://python-future.org/index.html) is a greate resource for examples when trying to achieve Python 2 and Python 3 compatibility.

> i don't know if you noticed or not (i thought i had updated this forum), but i created a fake RfCat dongle class which basically emulates some of the functionality of the dongle, in order to unit-test the python library.

Awesome! This would allow us to setup automated using Travis for example. If @atlas0fd00m  is open to this I would like to take a look at this next weekend. In the near future I will be very busy with other projects, but perhaps I can find spare time in between projects to get this going again.

**Comment by atlas0fd00m** [comment]
yes please!  i have been attempting to build a working travis config, but it's not quite working yet ("future" dependencies, apparently).  feel free to make it work :)

**Comment by atlas0fd00m** [comment]
oh, now it makes me out to be a liar, now it's failing on import usb. :)  well, i guess i got the future problem fixed.

**Comment by PlantDaddy** [comment]
In the PR I have open (and have some things to fix) I am also doing this as well. Unless someone else is already doing  this work. Dont want to step on toes

**Comment by atlas0fd00m** [comment]
based on the wonderful work of @PlantDaddy and @roaldnefs and others, https://github.com/atlas0fd00m/rfcat/releases/tag/v1.9.1

please review and break it.  if there's a shred that doesn't work well on *either* Python2 or Python3 i want to hear it.

we're very close to a v2.0.0 release with committed, tested Python3 support.  please help make this a reality sooner than later by issuing PRs and bug reports for Python3 issues in particular.  

also, check out the new unit tests and the FakeRfCat which are used for unittesting without hardware.

i believe @PlantDaddy had a number of other things he wanted to change for the betterment of maintaining a good codebase going forward,  so look forward to that as well.

next hurdle:  PYPI

**Comment by atlas0fd00m** [comment]
hey all,
RfCat v1.9.2 has been released on github (https://github.com/atlas0fd00m/rfcat/releases/tag/v1.9.2 as well as on PyPi.

please look through and find bugs :)

choose one or all of the following

pip install -U rfcat
download the release from github and install/use it
git clone/pull to update to the latest version
we're trying to make sure all the code is Python3 ready, so BREAK IT and help us be confident that all the nooks and crannies are working well. bug reports are good. Pull Requests (PR) on github are better. PR's with unit tests for some part of the code are even better still! if you have any questions about any of these options, reach out to me here or at my personal email address atlas@<redacted_check_your_email_notifications> unittests are pretty easy to make, PR's are pretty easy to make. but both are a lot easier after your first time, and i'm happy to help there too.
