### ISSUE TITLE
Why 2 .hex files?

### ISSUE THREAD

**Issue by carlosgonz0** [atlas0fd00m/rfcat#153]
Releases v2.0.1: heatwave
 
RfCatYS1CCBootloader-201231.hex => So this seems firmware to ys1 bootloader.RfCatYS1
RfCatYS1-201231.hex => This file is for what?

I thankful for all the help to my confuse.

**Comment by atlas0fd00m** [comment]
one is meant to be loaded using the bootloader (ie. flash updates over USB, without external hardware).
the other is meant for flashing directly to the CC1111, and requires an external hardware programmer/debugger.

let me know if this doesn't make sense.

**Comment by carlosgonz0** [comment]
> let me know if this doesn't make sense.

Thank you very much  atlas0fd00m i understand now!
