### ISSUE TITLE
yardstick1 firmware update - Something is talking to the RfCat dongle (Modem Manager, most likely)

### ISSUE THREAD

**Issue by demuxr** [atlas0fd00m/rfcat#20]
Hi, I am a n00b to ys1 & rfcat. I want to install the latest firmware on the ys1.

First qn is: what is the latest firmware version? I have 0450 - is that old?

My OS is Kali 2018.2, and I'm running everything as root. I've cloned the git repo https://github.com/atlas0fd00m/rfcat
I don't have a debugger, so am just connecting the ys1 to my laptop via USB.
When I run the "make clean installRfCatYS1CCBootloader", the compilation succeeds, and the all ys1 LED's go solid (1,2,3: GREEN, RED, ORANGE) (so I assume the ys1 is in bootloader mode), but it then just loops forever with the message 

_"Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient."_

I tried "apt-get purge modemmanager" but it made no difference.

What am I doing wrong?

----------------- below is some output to show you what I mean ---------------
# confirm ys1 & rfcat is working
rfcat -r
In [3]: d.printRadioConfig()
== Hardware ==
Dongle:              YARDSTICKONE
Firmware rev:        0450
Compiler:            SDCCv350
Bootloader:          CC-Bootloader

== Software ==
rflib rev:           65535

# try firmware upgrade
cd rfcat
sudo cp etc/udev/rules.d/20-rfcat.rules /etc/udev/rules.d
sudo udevadm control --reload-rules

cd firmware
make clean installRfCatYS1CCBootloader

==== CLEANING STUFF UP ====
rm -f *.ihx *.rel *.hex *.sym *.asm *.lst *.lnk *.map *.mem *.rst
#./new_serial.py
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE  -DUSB_DEVICE_SERIAL_NUMBER="`./new_serial.py`" -c chipcon_usb.c
[--- new serial number: 0000 ---]
chipcon_usb.c:681: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:765: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:1286: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:1286: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c chipcon_usbdebug.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c chipcon_dma.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c bootloader.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c cc1111rf.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c global.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c cc1111_aes.c

==RfCatYS1CCBootloader.hex building==
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` --xram-loc 0xF000  --code-loc 0x1400 appFHSSNIC.c chipcon_usb.rel chipcon_usbdebug.rel chipcon_dma.rel bootloader.rel cc1111rf.rel global.rel cc1111_aes.rel -DYARDSTICKONE -DCC1111 -DUSBDEVICE
packihx <appFHSSNIC.ihx >bins/RfCatYS1CCBootloader.hex
packihx: read 611 lines, wrote 1178: OK.
if [ ! -c /dev/RFCAT_BL_YS1 ] ; then ../rfcat --bootloader --force && sleep 1 ; fi ;
Entering RfCat Bootloader mode, ready for new image...
rfcat_bootloader /dev/RFCAT_BL_YS1 erase_all

**Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.**

**Comment by jrb** [comment]
I found the symlink for the bootloader points to the wrong place. When my YS1 is in bootloader mode, /dev/RFCAT_BL_YS1 exists, but rfcat_bootloader fails to open it with an invalid ioctl (you have to hack in debug prints; the "something is talking to" actually means "I couldnt open it as a serial port".

fortunately I sound when the ys1 is in bootloader mode, I *also* have a /dev/ttyACM0 (your dev name may vary). this worked with rfcat_bootloader as RFCAT_BL_YS1 was expected to.

**Comment by atlas0fd00m** [comment]
hey jared,

thanks for the comment.  what was wrong?  invalid ioctl?  you are able to flash the /dev/ttyACM0 but not the /dev/RFCAT_BL_YS1?
yes, the bootloader script is not terribly robust (error handling when you can't talk to the dongle).  typically when you can't talk to the /dev/RFCAT_BL_* it is because NetworkManager is trying to open it as a modem.  at least that's historically what's been wrong.

can you give any other insight?  /dev/RFCAT_BL_YS1 should work just as well (if not better) as /dev/ttyACM0, assuming you don't have multiple RfCats plugged in or some other oddity.

thanks!
@

**Comment by jrb** [comment]
This is the output of rfcat_bootloader patched to print the exception:
```
$ rfcat_bootloader /dev/RFCAT_BL_YS1 erase_all
Could not configure port: (25, 'Inappropriate ioctl for device')

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.
^CTraceback (most recent call last):
  File "/usr/bin/rfcat_bootloader", line 216, in <module>
    time.sleep(6)
KeyboardInterrupt
```

You can see the usb device (all removed entries are completely unrelated to YS1)
```
lsusb
...snip...
Bus 001 Device 035: ID 1d50:605c OpenMoko, Inc. YARD Stick One bootloader
...snip...
```

The RFCAT symlink points to the /dev/bus entry:
```
$ file /dev/RFCAT_BL_YS1 
/dev/RFCAT_BL_YS1: symbolic link to bus/usb/001/035
```

For good measure, here are my udev rules (slightly modifies from yours, but should behave similarly)

```
# legacy RfCats and cc1111usb
SUBSYSTEMS=="usb" ATTRS{idVendor}=="0451" ATTRS{idProduct}=="4715" MODE:="0660" SYMLINK+="RFCAT%n" GROUP="rfcat"

# modern RfCats
SUBSYSTEMS=="usb" ATTRS{idVendor}=="1d50" ATTRS{idProduct}=="6047" MODE:="0660" SYMLINK+="RFCAT%n" GROUP="rfcat"
SUBSYSTEMS=="usb" ATTRS{idVendor}=="1d50" ATTRS{idProduct}=="6048" MODE:="0660" SYMLINK+="RFCAT%n" GROUP="rfcat"
SUBSYSTEMS=="usb" ATTRS{idVendor}=="1d50" ATTRS{idProduct}=="605b" MODE:="0660" SYMLINK+="RFCAT%n" GROUP="rfcat"


# RfCat bootloader subsystem (uses it's own product id)
SUBSYSTEMS=="usb" ATTRS{idVendor}=="1d50" ATTRS{idProduct}=="6049" MODE:="0660" SYMLINK+="RFCAT_BL_C" ENV{ID_MM_DEVICE_IGNORE}="1" GROUP="rfcat"
SUBSYSTEMS=="usb" ATTRS{idVendor}=="1d50" ATTRS{idProduct}=="604a" MODE:="0660" SYMLINK+="RFCAT_BL_D" ENV{ID_MM_DEVICE_IGNORE}="1" GROUP="rfcat"
SUBSYSTEMS=="usb" ATTRS{idVendor}=="1d50" ATTRS{idProduct}=="605c" MODE:="0660" SYMLINK+="RFCAT_BL_YS1" ENV{ID_MM_DEVICE_IGNORE}="1" GROUP="rfcat"
SUBSYSTEMS=="usb" ATTRS{idVendor}=="1d50" ATTRS{idProduct}=="ecc0" MODE:="0660" SYMLINK+="RFCAT_BL_SRF" ENV{ID_MM_DEVICE_IGNORE}="1" GROUP="rfcat"
```

**Comment by jrb** [comment]
see #35 for my PR
