### ISSUE TITLE
LED 1 inactive, and errors

### ISSUE THREAD

**Issue by HackingIntoYourHeart** [atlas0fd00m/rfcat#22]
LED 1 is not active. This YardStick One I bought quit on me after a week. $130, and I'm peeved. 

Output, no matter what I try:
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)

I cannot solve this issue. There is nothing on the web describing my problem. I can't enter bootloader mode. This issue is prevalent no matter what computer I try it on. LED 2 and 3 light up, but not one. This doesn't make any sense, as LED 1 means "initialized" and 2 and 3 are regarding TX and RX being active. Can someone PLEASE help me?! I don't know where else to turn!

**Comment by howudodat** [comment]
I seem to have the same problem.  Brand new YS1, rfcat reports: Error in resetup():Exception('No Dongle Found. Please insert a RFCAT dongle.',)

lsusb doesn't show the dongle, syslog is quiet, with no entries.

**Comment by atlas0fd00m** [comment]
hmmm..  @mossmann ?

if it doesn't show up in lsusb or syslog, it's almost guaranteed a hardware issue of some sort.  could be laptop, but more likely a YS1 issue (unflashed by some unlikely chance?)

**Comment by mossmann** [comment]
@nebula-cpp's issue was resolved over here: https://github.com/greatscottgadgets/yardstick/issues/2

@howudodat: If you are shorting pins 7 and 9 at power-on to activate the bootloader and you are not seeing all three LEDs illuminate, you should request a replacement from your reseller.

**Comment by pipi111** [comment]
hi i have just reset my dongle.
now i made a coonection to pin7 and 9 and i have all 3 led on. so it should be on bootloader mode
but when i go to install the bootloader on the hardware ,i have the same message 

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.

what im doing wrong 

rfcat_bootloader download '/root/Downloads/rfcat-master/firmware/CCBootloader/CCBootloader-rfcat-ys1.hex' 

how im going to recovered from brick.
this is not an hardware fault

**Comment by atlas0fd00m** [comment]
closing this for now.  @pipi111 if this is still an issue, please let me know.
