### ISSUE TITLE
Please tag some releases

### ISSUE THREAD

**Issue by rhertzog** [atlas0fd00m/rfcat#25]
Hello,

when rfcat was hosted on bitbucket, you used to make regular releases:
https://bitbucket.org/atlas0fd00m/rfcat/downloads/?tab=downloads (see rfcat_*.tar.gz)

But here on GitHub, there are no real versioned releases. Can you resume doing that please?
It really helps us to ensure we have the latest version in Kali because we have tools monitoring new releases.

Thank you in advance.

**Comment by atlas0fd00m** [comment]
thanks @rhertzog 
this is good feedback.  i'll set some alerts for myself to do so.
