### ISSUE TITLE
chars default to unsigned in sdcc 3.6+

### ISSUE THREAD

**Issue by jrb** [atlas0fd00m/rfcat#37]
prior to sdcc 3.6.0, the compiler's default behavior was to assume all `char`s were signed. the default is now to they're unsigned. 

either `-fsigned-chars` should be added to the compiler flags when 3.6+ is detected, or all chars should be explicitly defined signed/unsigned.

**Comment by atlas0fd00m** [comment]
wow, thank you, @jrb jrb.  i don't know how i missed this.  many github notifications have been lost for me.  i'll look into this.
this could be why firmware broke after 3.5.0.  i'm not sure how this breaks the firmware, but somehow pings fail on later firmwares.
