### ISSUE TITLE
rfcat start and undifined Terminal

### ISSUE THREAD

**Issue by peseta3** [atlas0fd00m/rfcat#38]
I don´t know it is an Issue. I don`t think so.
If I type 
_**root@kali:**_cd rfcat_150225# sudo rfcat -r

I get only in Green
In (1):

Where is the starting mode with some infos about to type in orinfos about the YS1?
I have Python 2.7 I think???? or ipython?? I don´t know.
Anyone a Idea?

**Comment by atlas0fd00m** [comment]
as for commands:
`
$ rfcat -h
`
and from within rfcat:

```
$ rfcat -r
>>> d.<tab>
  or
>>> help(d)
```
for config info:
```
>>> d.printRadioConfig()
```

**Comment by peseta3** [comment]
ah, cool
thanks a lot.
great
