### ISSUE TITLE
Error in resetup():ChipconUsbTimeoutException()

### ISSUE THREAD

**Issue by cosmo6110** [atlas0fd00m/rfcat#39]
Hi!
I did a firmware update (make clean installRfCatYS1CCBootloader).
It went well with the update, but i cant use the my Yardstick one any more.
Maybe the bootloader is corrupted? (Error in resetup():ChipconUsbTimeoutException()).
It's no response from  the rfcat program on the dongle.
I running the dongle on the latest Kali, 

Product: YARD Stick One
[ 1994.878685] usb 1-1.3: Manufacturer: Great Scott Gadgets
[ 1994.878696] usb 1-1.3: SerialNumber: 0000
Bus 001 Device 013: ID 1d50:605b OpenMoko, Inc.

I have reflashed the dongle couple of time, with jumper between pin 7 9.
It works,  but no respond from the yardstick.
Tested on another computer same story.
so i'm little stuck here, what to do?

Maybe i must get a jtag?
Any ideas?

**Comment by cosmo6110** [comment]
File "/usr/local/bin/rfcat", line 56, in <module>
    interactive(ifo.index, DongleClass=RfCat, intro=intro)
  File "/usr/local/lib/python2.7/dist-packages/rflib/__init__.py", line 207, in interactive
    d.setModeRX()       # this puts the dongle into receive mode
  File "/usr/local/lib/python2.7/dist-packages/rflib/chipcon_nic.py", line 334, in setModeRX
    self.setRfMode(RFST_SRX)
  File "/usr/local/lib/python2.7/dist-packages/rflib/chipcon_nic.py", line 319, in setRfMode
    r = self.send(APP_SYSTEM, SYS_CMD_RFMODE, "%c" % (self._rfmode) + parms)
  File "/usr/local/lib/python2.7/dist-packages/rflib/chipcon_usb.py", line 705, in send
    return self.recv(app, cmd, wait)
  File "/usr/local/lib/python2.7/dist-packages/rflib/chipcon_usb.py", line 669, in recv
    raise ChipconUsbTimeoutException
rflib.chipcon_usb.ChipconUsbTimeoutException: Timeout waiting for USB response.

**Comment by atlas0fd00m** [comment]
thanks for updating this.  if you have a chance, i'd be interested in what errors/problems you saw wrt SDCC v3.8, since that's going to be the norm at some point and i'd like RfCat code to be ready.

thanks!
@

**Comment by Loumiakas** [comment]
@atlas0fd00m: I see that this particular issue was closed, however, I think this still needs to be fixed (I saw some closed [issues](https://github.com/atlas0fd00m/rfcat/issues/42) regarding same issue). I have tested out firmware installation with different versions of sdcc starting from 3.5.0 and noticed that firmware upgrade with latest (3.8.0) will cause this error (and device is rendered unusable) . Here are two samples of important stuff printed during installation between 3.5.0 and 3.8.0:

```
sdcc 3.5.0
[--- new serial number: 0000 ---]
chipcon_usb.c:681: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:765: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:1324: warning 230: label without statement
chipcon_usb.c:1302: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:1302: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
global.c:36: warning 94: comparison is always true due to limited range of data type
global.c:56: warning 126: unreachable code
global.c:57: warning 126: unreachable code
global.c:57: warning 126: unreachable code
packihx: read 617 lines, wrote 1187: OK.
```
```
sdcc 3.8.0
[--- new serial number: 0000 ---]
chipcon_usb.c:681: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:765: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:1324: warning 230: label without statement
chipcon_usb.c:1302: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:1302: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
global.c:36: warning 94: comparison is always true due to limited range of data type
global.c:56: warning 126: unreachable code
global.c:57: warning 126: unreachable code
global.c:57: warning 126: unreachable code
packihx: read 618 lines, wrote 1188: OK.
```
As I don't have enough knowledge on how firmware data is generated, I cannot fix it. I can however, provide any information you need to get to the bottom of this.

P.S. packihx seems to read and write an extra line with sdcc 3.8.0 (might not be significant)

<img width="1262" alt="Screenshot 2019-04-04 at 21 59 28" src="https://user-images.githubusercontent.com/44226245/55588165-f9a09280-5724-11e9-8d5b-dee5c7785223.png">

**Comment by roaldnefs** [comment]
Ran in the same issue today... I'm currently running Ubuntu 19.04 and thus installed sdcc version 3.9.0, which results in the same errors as #42. Version 3.5.0 of sdcc seems to work fine. You can get the YS1 in bootloader mode by grounding pin 7 and pin 9 ([enter bootloader mode when the firmware isn't running](https://github.com/greatscottgadgets/yardstick/wiki/Frequently-Asked-Questions#q-my-firmware-isnt-running-how-do-i-enter-bootloader-mode)).

**Comment by ssbernabeu** [comment]
I am currently using version 3.5.0 but still get the _rflib.chipcon_usb.ChipconUsbTimeoutException: Timeout waiting for USB response_ error when I run any listening command from a Python script and don't hear anything. Any ideas why this might be? I am an absolute noob so I may be missing something

**Comment by SorenAndreasen** [comment]
I too am running sdcc 3.5.0 but also getting this error constantly. Help would be very very appreciated. cheers

**Comment by atlas0fd00m** [comment]
> ChipconUsbTimeoutException: Timeout waiting for USB response error when I run any listening command from a Python script and don't hear anything.

that's the normal behavior.  you can adjust it, but it is necessary to avoid having to Ctrl-C while waiting for data.  i never realized how confusing it may be to use the ChipconUsbTimeoutException for RF timeout.  RFrecv() hands its timeout into ChipconUsb's recv() function, which throws ChipconUsbTimeoutException if it doesn't receive a message in the allotted time.

is there anything that doesn't jive with this explanation?  if it's something else odd, i'd like to hear it.
