### ISSUE TITLE
YS1 failed to update the firmware.

### ISSUE THREAD

**Issue by gusevargas** [atlas0fd00m/rfcat#41]
I'm a bit of a noob, I attempted to update the firmware on two different YS1. And received the same message from them, which apparently, there is no notes or any previous reported issues for it...

==RfCatYS1CCBootloader.hex building==
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` --xram-loc 0xF000  --code-loc 0x1400 appFHSSNIC.c chipcon_usb.rel chipcon_usbdebug.rel chipcon_dma.rel bootloader.rel cc1111rf.rel global.rel cc1111_aes.rel -DYARDSTICKONE -DCC1111 -DUSBDEVICE
tee: .revision: Permission denied
appFHSSNIC.c:1371: error 4: 'fopen' failed on file 'appFHSSNIC.asm'
Makefile:98: recipe for target 'RfCatYS1CCBootloader.hex' failed
make: *** [RfCatYS1CCBootloader.hex] Error 1

Any help or support with these units, would be appreciated

**Comment by gusevargas** [comment]
I have been doing some tinkering, and after modifying the 20-rfcat.rules files, I know get a different message, which calls for a serial module, which unfortunately, doesn't exist, since I am connecting over USB. 
If anyone could shed some light on this issue, I would be very grateful.

==RfCatYS1CCBootloader.hex building==
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` --xram-loc 0xF000  --code-loc 0x1400 appFHSSNIC.c chipcon_usb.rel chipcon_usbdebug.rel chipcon_dma.rel bootloader.rel cc1111rf.rel global.rel cc1111_aes.rel -DYARDSTICKONE -DCC1111 -DUSBDEVICE
packihx <appFHSSNIC.ihx >bins/RfCatYS1CCBootloader.hex
packihx: read 621 lines, wrote 1197: OK.
if [ ! -c /dev/RFCAT_BL_YS1 ] ; then ../rfcat --bootloader --force && sleep 1 ; fi ;
rfcat_bootloader /dev/RFCAT_BL_YS1 erase_all
Traceback (most recent call last):
  File "/usr/local/bin/rfcat_bootloader", line 5, in <module>
    import serial
ImportError: No module named serial
Makefile:370: recipe for target 'installRfCatYS1CCBootloader' failed
make: *** [installRfCatYS1CCBootloader] Error 1

**Comment by atlas0fd00m** [comment]
you need the python "serial" module.  also, rfcat currently expects python 2.x, so if you have python3 installed as default, it may cause issues.

**Comment by gusevargas** [comment]
Thank you very much for the reply. I was able to install the serial module.
And that allowed me to update the firmware.
