### ISSUE TITLE
YS1 firmware update success but getting Chipcon Timeout when running rfcat

### ISSUE THREAD

**Issue by rbenzing** [atlas0fd00m/rfcat#42]
I got the latest firmware to install using the YS1 7 & 9 pin trick successfully without any errors. 
`rfcat_bootloader /dev/RFCAT_BL_YS1 verify bins/RfCatYS1CCBootloader.hex && rfcat_bootloader /dev/RFCAT_BL_YS1 run
Verifying 0003 bytes at address: 5AF1 (OK) Skipping non data record: ':00000001FF'`

However now when I plug it in and run rfcat -r it gives me the following error:

Error in resetup():ChipconUsbTimeoutException()

when i run with `sudo` i get:

Error in resetup():USBError(110, u'Operation timed out')

looking in /dev/ I see:
/dev/RFCAT3 (plugged into 3rd usb port)

What did I do wrong?

**Comment by mossmann** [comment]
Is it possible that your firmware and host code are not the same version?

To check the version of your source repository after you have built firmware:
```
cd rfcat
cat .revision
```
(My current revision is 531.)

To re-install the host code:
```
python2 setup.py build && sudo python2 setup.py install
```

**Comment by rbenzing** [comment]
I re-installed the host code however still getting the error with revision 531:
`
Error in resetup():ChipconUsbTimeoutException()
Traceback (most recent call last):
  File "/usr/local/bin/rfcat", line 58, in <module>
    interactive(ifo.index, DongleClass=RfCat, intro=intro)
  File "/usr/local/lib/python2.7/dist-packages/rflib/__init__.py", line 207, in interactive
    d.setModeRX()       # this puts the dongle into receive mode
  File "/usr/local/lib/python2.7/dist-packages/rflib/chipcon_nic.py", line 334, in setModeRX
    self.setRfMode(RFST_SRX)
  File "/usr/local/lib/python2.7/dist-packages/rflib/chipcon_nic.py", line 319, in setRfMode
    r = self.send(APP_SYSTEM, SYS_CMD_RFMODE, "%c" % (self._rfmode) + parms)
  File "/usr/local/lib/python2.7/dist-packages/rflib/chipcon_usb.py", line 705, in send
    return self.recv(app, cmd, wait)
  File "/usr/local/lib/python2.7/dist-packages/rflib/chipcon_usb.py", line 669, in recv
    raise ChipconUsbTimeoutException
rflib.chipcon_usb.ChipconUsbTimeoutException: Timeout waiting for USB response.
`
I did notice some warnings on building the firmware perhaps these can give some insight..I am lost in translation trying to figure this out.

`
#./new_serial.py
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE  -DUSB_DEVICE_SERIAL_NUMBER="`./new_serial.py`" -c chipcon_usb.c
[--- new serial number: 0004 ---]
chipcon_usb.c:681: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:765: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:1324: warning 230: label without statement
chipcon_usb.c:1302: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:1302: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
`

Is there a way to define the serial device? I think it may be choosing the wrong serial device.

**Comment by mossmann** [comment]
To avoid firmware compilation issues for now, can you try installing this firmware binary (revision 531)?
https://gist.github.com/mossmann/7b816680df2ac513df3835f3cb9eaa1b

**Comment by rbenzing** [comment]
That worked! must be my build process. Thanks a bunch.

**Comment by jfdhuiz** [comment]
I followed this guide to upgrade my firmware https://roaldnefs.com/blog/yard-stick-one-firmware/ (which doesn't mention that you could backup it).

I'm having the same issue, with 543 @ Kali 2019.2 with sdcc 3.8

I rebooted the machine, problem persists.

I ground pin 7 and 9, but it doesn't change anything.

When I do $ rfcat_bootloader /dev/RFCAT5 verify RfCatYS1CCBootloader.hex

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.  (error: SerialException("Could not configure port: (25, 'Inappropriate ioctl for device')",))

Checking lsof ModemManager is not doing anything fancy. I killed ModemManager, same errors persist.

I'd love to install a different firmware but it doesn't seem I can communicate with the device anymore.

**Comment by jfdhuiz** [comment]
I made a different connector which fixed the issue. I made both from those plastic things which connect cables together (they contain metal in the middle). Apparently the metal I was using to connect the 2 pins did not work (well enough). I've seen lights light up, but never all 3. The second one worked right away.

I used Ubuntu 18.04 LTS to fix the issue (with SDCC 3.5), but I'm not sure it matters, because using that with the first (broken) connector did not fix the issue.

Glad I didn't brick it....

**Comment by roaldnefs** [comment]
Ran in the same issue a @jfdhuiz today... I'm currently running Ubuntu 19.04 and thus installed sdcc version 3.9.0, which results in the same errors as #39. Version 3.5.0 of sdcc seems to work fine. You can get the YS1 in bootloader mode by grounding pin 7 and pin 9 ([enter bootloader mode when the firmware isn't running](https://github.com/greatscottgadgets/yardstick/wiki/Frequently-Asked-Questions#q-my-firmware-isnt-running-how-do-i-enter-bootloader-mode)).

I was able to ground pin 7 and pin 9 on the YS1 using a paperclip.

![IMG_20190607_115025](https://user-images.githubusercontent.com/6523325/59096805-0788b480-891c-11e9-9956-8a1d1e963ea2.jpg)

Note: I will update the blogpost @jfdhuiz is referring to...

**Comment by diegocr** [comment]
I'm considering purchasing the YS1, just wondering if anybody is using it on Ubuntu 22.04 ?

Thanks.

**Comment by diegocr** [comment]
Well, cannot wait for an answer and purchased it anyway, _seems_ to be working 🎉 

```
In [1]: print(d.reprRadioConfig())
== Hardware ==
Dongle:              b'YARDSTICKONE'
Firmware rev:        b'0606\x00'
Compiler:            b'SDCCv350\x00'
Bootloader:          CC-Bootloader

== Software ==
rflib rev:           636
```

Next I just need to figure how to use this thing to capture the signal of my TTGO(TG3) remote to automate raising and lowering blinds, my first time ever with this kind of equipment / HA stuff 👀
