### ISSUE TITLE
installing rfcat on YS1 serial.serialutil.SerialException: device reports readiness to read but returned no data

### ISSUE THREAD

**Issue by howudodat** [atlas0fd00m/rfcat#43]
~/rfcat/firmware# rfcat_bootloader /dev/RFCAT_BL_YS1 read 0x0000 0x00FF
Traceback (most recent call last):
  File "/usr/local/bin/rfcat_bootloader", line 264, in <module>
    flash_read(ihx_file, serial_port, int(options[0], 16), int(options[1], 16))
  File "/usr/local/bin/rfcat_bootloader", line 140, in flash_read
    for line in serial_port:
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 495, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

~/rfcat/firmware# lsusb -v -s 001:005
Bus 001 Device 005: ID 1d50:605c OpenMoko, Inc. 

~/rfcat/firmware# ls -l /dev/RFCAT_BL_YS1 
lrwxrwxrwx 1 root root 7 Mar 20 14:07 /dev/RFCAT_BL_YS1 -> ttyACM0
~/rfcat/firmware# ls -l /dev/ttyACM0
crw-rw---- 1 root dialout 166, 0 Mar 20 15:18 /dev/ttyACM0

~/rfcat/firmware# groups
root dialout

**Comment by mossmann** [comment]
Does this happen with the latest version of rfcat (specifically rfcat_bootloader) installed?
