### ISSUE TITLE
errors on upgrading the firmware

### ISSUE THREAD

**Issue by pipi111** [atlas0fd00m/rfcat#45]
hi
Im stuck with a yardstickone bootloader 

root@kali:~/rfcat/firmware# lsusb
Bus 002 Device 018: ID 1d50:605c OpenMoko, Inc. YARD Stick One bootloader
--------------------------------------------------------------------------------------------------------------------
root@kali:~/rfcat/firmware# groups
root 
---------------------------------------------------------------------------------------------------------------
root@kali:~/rfcat/firmware# rfcat_bootloader 000001 download CCBootloader-rfcat-ys1.hex

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.
c^CTraceback (most recent call last):
  File "/usr/local/bin/rfcat_bootloader", line 215, in <module>
    time.sleep(6)
KeyboardInterrupt
------------------------------------------------------------------------------------------------------------------

[ 8726.842708] usb 2-1.1.1: new full-speed USB device number 16 using ehci-pci
[ 8726.954436] usb 2-1.1.1: New USB device found, idVendor=1d50, idProduct=605c, bcdDevice= 0.10
[ 8726.954441] usb 2-1.1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 8726.954444] usb 2-1.1.1: Product: YARD Stick One Bootloader
[ 8726.954447] usb 2-1.1.1: Manufacturer: Great Scott Gadgets
[ 8726.954450] usb 2-1.1.1: SerialNumber: 000001
[ 8726.956079] cdc_acm 2-1.1.1:1.0: ttyACM0: USB ACM device

on my etc/udev/rules.d/20.rfcat.rules  i have  this 

# legacy RfCats and cc1111usb
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0451", ATTRS{idProduct}=="4715", MODE:="0660", SYMLINK+="RFCAT%n", GROUP="dialout"

# modern RfCats
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="6047", MODE:="0660", SYMLINK+="RFCAT%n", GROUP="dialout"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="6048", MODE:="0660", SYMLINK+="RFCAT%n", GROUP="dialout"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="605b", MODE:="0660", SYMLINK+="RFCAT%n", GROUP="dialout"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="ecc1", MODE:="0660", SYMLINK+="RFCAT%n", GROUP="dialout"

# RfCat bootloader subsystem (uses it's own product id)
SUBSYSTEM=="tty", SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="6049", MODE:="0660", SYMLINK+="RFCAT_BL_C", ENV{ID_MM_DEVICE_IGNORE}="1", GROUP="dialout"
SUBSYSTEM=="tty", SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="604a", MODE:="0660", SYMLINK+="RFCAT_BL_D", ENV{ID_MM_DEVICE_IGNORE}="1", GROUP="dialout"
SUBSYSTEM=="tty", SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="605c", MODE:="0660", SYMLINK+="RFCAT_BL_YS1", ENV{ID_MM_DEVICE_IGNORE}="1", GROUP="dialout"
SUBSYSTEM=="tty", SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="ecc0", MODE:="0660", SYMLINK+="RFCAT_BL_SRF", ENV{ID_MM_DEVICE_IGNORE}="1", GROUP="dialout"

Im not able to install  the firmware

**Comment by Loumiakas** [comment]
You are passing in device serial number as an argument `rfcat_bootloader 000001 download CCBootloader-rfcat-ys1.hex`. Instead, try passing in actual device 'location', which would be something like this `rfcat_bootloader /dev/RFCAT_BL_YS1 download CCBootloader-rfcat-ys1.hex`

**Comment by atlas0fd00m** [comment]
thanks for fielding this question, @Loumiakas !
