### ISSUE TITLE
unable to flash FW on Mac OS

### ISSUE THREAD

**Issue by trunkafunk** [atlas0fd00m/rfcat#47]
I think I have things setup correctly, however I'm not seeing any RFCAT ports enumerated in /dev.

After 
sudo rfcat --bootloader --force
I see the 3 lights lit.

BiffRaff:lsusb graypowell$ ls -lrt /dev/ |grep usb
crw-rw-rw-  1 root        wheel           18,  14 Apr 17 16:12 tty.usbmodem0000011
crw-rw-rw-  1 root        wheel           18,  15 Apr 17 16:15 cu.usbmodem0000011

Now when trying to flash the code I see:
sudo ./rfcat_bootloader /dev/cu.usbmodem0000011 download ../firmware/CCBootloader/CCBootloader-rfcat-ys1.hex 
Writing :0600000002017B02140363  RC = 3 (Bad Address)
Error downloading code!

I don't have a JTAG board so I guess I shouldn't be using goodfet to try and flash, correct?

**Comment by trunkafunk** [comment]
I've never gotten the RFCAT_BL_YS1 to enumerate.

BiffRaff:firmware graypowell$ make clean installRfCatYS1CCBootloader

==== CLEANING STUFF UP ====
rm -f *.ihx *.rel *.hex *.sym *.asm *.lst *.lnk *.map *.mem *.rst
#./new_serial.py
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE  -DUSB_DEVICE_SERIAL_NUMBER="`./new_serial.py`" -c chipcon_usb.c
[--- new serial number: 0000 ---]
chipcon_usb.c:681: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:765: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:1324: warning 230: label without statement
chipcon_usb.c:1302: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:1302: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c chipcon_usbdebug.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c chipcon_dma.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c bootloader.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c cc1111rf.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c global.c
global.c:36: warning 94: comparison is always true due to limited range of data type
global.c:56: warning 126: unreachable code
global.c:57: warning 126: unreachable code
global.c:57: warning 126: unreachable code
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c cc1111_aes.c


==RfCatYS1CCBootloader.hex building==
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` --xram-loc 0xF000  --code-loc 0x1400 appFHSSNIC.c chipcon_usb.rel chipcon_usbdebug.rel chipcon_dma.rel bootloader.rel cc1111rf.rel global.rel cc1111_aes.rel -DYARDSTICKONE -DCC1111 -DUSBDEVICE
packihx <appFHSSNIC.ihx >bins/RfCatYS1CCBootloader.hex
packihx: read 627 lines, wrote 1205: OK.
if [ ! -c /dev/RFCAT_BL_YS1 ] ; then ../rfcat --bootloader --force && sleep 1 ; fi ;
Entering RfCat Bootloader mode, ready for new image...
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
rfcat_bootloader /dev/RFCAT_BL_YS1 erase_all

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.


Here's previous output for getinfo:
>>> print(d.reprRadioConfig())
== Hardware ==
Dongle:              YARDSTICKONE
Firmware rev:        0348
Compiler:            Not found! Update needed!
Bootloader:          CC-Bootloader

== Software ==
rflib rev:           542

== Frequency Configuration ==
Frequency:           901999877.929688 hz (0x259555)
Channel:             0
Intermediate freq:   281250 hz
Frequency Offset:    0 +/-
Est. Freq Offset:    226

== Modem Configuration ==
Modulation:          2FSK
DRate:               38360.595703 hz
ChanBW:              93750.000000 hz
DEVIATION:           20507.812500 hz
Sync Mode:           15 of 16 bits must match
Min TX Preamble:     4 bytes
Chan Spacing:        199951.171875 hz
BSLimit:             No data rate offset compensation performed
DC Filter:           enabled
Manchester Encoding: disabled
Fwd Err Correct:     disabled

== Packet Configuration ==
Sync Word:           0x0C4E
Packet Length:       255
Length Config:       Fixed Packet Mode
Configured Address:  0x0
Preamble Quality Threshold: 4 * 2
Append Status:       No
Rcvd Packet Check:   No address check
Data Whitening:      off
Packet Format:       Normal mode
CRC:                 disabled

== AES Crypto Configuration ==
AES Mode:            CBC - Cipher Block Chaining
Crypt RF Input:      off
Crypt RF Output:     off

== Radio Test Signal Configuration ==
TEST2:               0x88
TEST1:               0x31
TEST0:               0x9
VCO_SEL_CAL_EN:      0x0

== Radio State ==
     MARCSTATE:      MARC_STATE_RX (d)
     DONGLE RESPONDING:  mode :d, last error# 1

== Client State ==
========================================================================================================================
     client thread cycles:      61/14
     client errored cycles:     0
     recv_queue:                (0 bytes) ''
     trash:                     (3 blobs) "[128, 142, (1555539398.869655, '')]"
     recv_mbox                  (2 keys)  "['0x42', '0xff']"
       app 0x42 (2 records)
             [0x1]    (1 frames)  "[('B\x01\xff\x00\x0f\x85:\x8f,x/\xd3\xf9N\xf03[\xbf\xfa\x07\xfao\xa6\xf6\x9a@\x9bc\x"
             [0x7]    (0 frames)  "[]"

       app 0xff (4 records)
             [0x88]    (0 frames)  "[]"
             [0x80]    (0 frames)  "[]"
             [0x82]    (0 frames)  "[]"
             [0x86]    (0 frames)  "[]"



BiffRaff:CC-Bootloader graypowell$ ./rfcat_bootloader /dev/ttys000 download ../firmware/CCBootloader/CCBootloader-rfcat-ys1.hex 

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.

**Comment by trunkafunk** [comment]
Just tried this on an ubuntu install and I'm still getting the bad address issue.

**Comment by atlas0fd00m** [comment]
what does your /etc/udev/rules.d/20-rfcat.rules look like?

**Comment by atlas0fd00m** [comment]
correct, you should be using the bootloader... but the firmware for the bootloader is different than if you flash it directly....

oh, you should be using the firmware you created, not the CCBootloader code.

the firmware you compiled shouljd be  <RFCAT_HOME>/firmware/bins/RfCatYS1CCBootloader.hex

**Comment by trunkafunk** [comment]
The problem I seem to be having now is that I can’t get the modem in forced bootloader mode.
I finally got it to restore a FW, which succeeded, but I’ve have no communication since.
(One doesn’t need to use the ‘run’ command do they?) 

I tried jumpering pin 2 to ground on device insert and I get a momentary blink and then nothing. 

Sorry I’m returning to Bootloader world after a Haitus. What is required to ‘make’ the  /firmware/nine/RfCatYS1CCBootloader.hex file?  I tried on by Ubuntu system and had some other dependency issues (possibly due to using virtual box?)

Thanks!
-Gray

**Comment by atlas0fd00m** [comment]
should only require sdcc to build.  you already built it above:
`
BiffRaff:firmware graypowell$ make clean installRfCatYS1CCBootloader
`

**Comment by atlas0fd00m** [comment]
it should have already made that file

**Comment by trunkafunk** [comment]
Thanks for the help, this is a tinker project and hoping I can get through this and onto the fun stuff :D


The problem now appears to be that I can’t force the device in boot loader mode (or rather I’m really misunderstanding something)
I should be able to just jumper pin 2 to ground (Pin 9 or GND) on device insert however I’m not getting the 3 LED’s lit anymore (And can’t seem to force it using rfcat or cc-bootloader)..

I did finally install a FW successfully at some point:
./rfcat_bootloader /dev/cu.usbmodem0000011 download ../firmware/bins/RfCatYS1CCBootloader.hex 
Writing :0614000002148B024C0DEA  RC = 0 (OK)
Writing :01140B0032AE  RC = 0 (OK)
Writing :0114130032A6  RC = 0 (OK)


However rfcat -r didn’t seem to work afterwards. And I didn’t get any cu/tty enumerations.
I don’t need to execute “run” afterwards right?


On my Mac system, after retrying:
BiffRaff:firmware graypowell$ make clean installRfCatYS1CCBootloader

==== CLEANING STUFF UP ====
rm -f *.ihx *.rel *.hex *.sym *.asm *.lst *.lnk *.map *.mem *.rst
#./new_serial.py
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE  -DUSB_DEVICE_SERIAL_NUMBER="`./new_serial.py`" -c chipcon_usb.c
[--- new serial number: 0000 ---]
chipcon_usb.c:681: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:765: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:1324: warning 230: label without statement
chipcon_usb.c:1302: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:1302: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c chipcon_usbdebug.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c chipcon_dma.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c bootloader.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c cc1111rf.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c global.c
global.c:36: warning 94: comparison is always true due to limited range of data type
global.c:56: warning 126: unreachable code
global.c:57: warning 126: unreachable code
global.c:57: warning 126: unreachable code
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c cc1111_aes.c


==RfCatYS1CCBootloader.hex building==
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` --xram-loc 0xF000  --code-loc 0x1400 appFHSSNIC.c chipcon_usb.rel chipcon_usbdebug.rel chipcon_dma.rel bootloader.rel cc1111rf.rel global.rel cc1111_aes.rel -DYARDSTICKONE -DCC1111 -DUSBDEVICE
packihx <appFHSSNIC.ihx >bins/RfCatYS1CCBootloader.hex
packihx: read 627 lines, wrote 1205: OK.
if [ ! -c /dev/RFCAT_BL_YS1 ] ; then ../rfcat --bootloader --force && sleep 1 ; fi ;
Entering RfCat Bootloader mode, ready for new image...
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
Error in resetup():ChipconUsbTimeoutException()
rfcat_bootloader /dev/RFCAT_BL_YS1 erase_all

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.

Something is talking to the RfCat dongle (Modem Manager, most likely).  Retrying again after 5 seconds.  This can take a minute, please be patient.
^CTraceback (most recent call last):
  File "/usr/local/bin/rfcat_bootloader", line 215, in <module>
    time.sleep(6)
KeyboardInterrupt
make: *** [installRfCatYS1CCBootloader] Error 1



-Gray

**Comment by atlas0fd00m** [comment]
that doesn't look like you flashed a valid RfCat firmware onto the device (unless you snipped out a *ton*).

what do you get on Linux in syslog when you plug in the device?
lsusb?

**Comment by trunkafunk** [comment]
Here’s what I’m getting on my Mac:

2019-04-22 14:33:18.012 system_profiler[2211:45599] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
Bus 020 Device 004: ID 2109:2817 VIA Labs, Inc. USB2.0 Hub 
Bus 020 Device 005: ID 2109:2817 VIA Labs, Inc. USB2.0 Hub 
Bus 020 Device 007: ID 2109:0100 VIA Labs, Inc. USB 2.0 BILLBOARD  Serial: 0000000000000001
Bus 020 Device 029: ID 1d50:605b 1d50 YARD Stick One  Serial: 0000
Bus 020 Device 000: ID 05ac:8600 Apple Inc. iBridge 
Bus 000 Device 001: ID 2109:0817 VIA Labs, Inc. USB3.0 Hub 
Bus 000 Device 004: ID 2109:0817 VIA Labs, Inc. USB3.0 Hub 
Bus 000 Device 003: ID 0bda:8153 Realtek Semiconductor Corp. USB 10/100/1000 LAN  Serial: 000001
Bus 000 Device 002: ID 05e3:0749 Genesys Logic, Inc. USB3.0 Card Reader  Serial: 000000001537
Bus 000 Device 001: ID 05ac:ISPT Apple Inc. USB 3.0 Bus 
Bus 001 Device 001: ID 05ac:CIAR Apple Inc. USB 3.1 Bus 
Bus 000 Device 001: ID 05ac:CIAR Apple Inc. USB 3.1 Bus 


The only thing of note I see in syslogs:
error	14:34:46.624376 -0700	efilogin-helper	Failed to set up CFPasteboardRef 'AppleIntlFileCacheModificationDatePasteboard'. Error: <error: 0x7fff982c9140> { count = 1, transaction: 0, voucher = 0x0, contents =
	"XPCErrorDescription" => <string: 0x7fff982c93e8> { length = 18, contents = "Connection invalid" }
}
default	14:34:46.838398 -0700	usbmuxd	notice    Log from 1-dfb0a62cf478204fabacb29f9e42c032c2c7520a@0x14100000: handleConnectResult new session to port 3838 failed: 61



If I short pins 2 and 9, it should force bootloader mode correct?  And I should see the 3 lights?

**Comment by atlas0fd00m** [comment]
yes.  and that looks like you have a valid RfCat YS1 firmware running.
i need to fix that Modem Manager message.  it's only sometimes the problem.

**Comment by atlas0fd00m** [comment]
try pulling the latest client (python) code and using its rfcat_bootloader (easiest way is just to install it, but you can use it in-place if you know what you're doing and want to)

**Comment by trunkafunk** [comment]
I think the problem on my MacOS system is that it’s not enumerating the YS1 in /dev/, I guess because of the udev stuff?
Any way I can manually find the serial, I don’t readily see it in /dev/

**Comment by trunkafunk** [comment]
Pulled client…

So yea on the ubuntu system I see

gray@gray-VirtualBox:~/rfcat/CC-Bootloader$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 004: ID 1d50:605b OpenMoko, Inc.
Bus 002 Device 003: ID 80ee:0021 VirtualBox USB Tablet
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

gray@gray-VirtualBox:~/rfcat/CC-Bootloader$ ls -lrt /dev/R*
lrwxrwxrwx 1 root root 15 Apr 22 14:33 /dev/RFCAT2 -> bus/usb/002/004


However when running the updated client:

gray@gray-VirtualBox:~/rfcat/CC-Bootloader$ ./rfcat_bootloader /dev/RFCAT2
download ../firmware/bins/RfCatYS1CCBootloader.hex

Something is talking to the RfCat dongle (Modem Manager, most likely).
Retrying again after 5 seconds.  This can take a minute, please be
patient.  (error: SerialException("Could not configure port: (25,
'Inappropriate ioctl for device')",))
^CTraceback (most recent call last):
  File "./rfcat_bootloader", line 215, in <module>
    time.sleep(6)
KeyboardInterrupt

You're saying it's already running FW so I feel like reflashing the
Bootloader not what I should be doing?



 Apr 23, 2019, at 9:17 AM, gray.powell <trunkafunk@gmail.com> wrote:


I think the problem on my MacOS system is that it’s not enumerating the YS1
in /dev/, I guess because of the udev stuff?
Any way I can manually find the serial, I don’t readily see it in /dev/




On Apr 23, 2019, at 6:18 AM, atlas0fd00m <notifications@github.com> wrote:

try pulling the latest client (python) code and using its rfcat_bootloader
(easiest way is just to install it, but you can use it in-place if you know
what you're doing and want to)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/atlas0fd00m/rfcat/issues/47#issuecomment-485799036>,
or mute
the thread

**Comment by trunkafunk** [comment]
gray@gray-VirtualBox:~/rfcat/firmware$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 004: ID 1d50:605b OpenMoko, Inc.
Bus 002 Device 002: ID 80ee:0021 VirtualBox USB Tablet
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

gray@gray-VirtualBox:~/rfcat/firmware$ make installRfCatYS1CCBootloader
==RfCatYS1CCBootloader.hex building==
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` --xram-loc 0xF000
--code-loc 0x1400 appFHSSNIC.c chipcon_usb.rel chipcon_usbdebug.rel
chipcon_dma.rel bootloader.rel cc1111rf.rel global.rel cc1111_aes.rel
-DYARDSTICKONE -DCC1111 -DUSBDEVICE
packihx <appFHSSNIC.ihx >bins/RfCatYS1CCBootloader.hex
packihx: read 621 lines, wrote 1197: OK.
if [ ! -c /dev/RFCAT_BL_YS1 ] ; then ../rfcat --bootloader --force && sleep
1 ; fi ;
Entering RfCat Bootloader mode, ready for new image...
Error in resetup():ChipconUsbTimeoutException()
rfcat_bootloader /dev/RFCAT_BL_YS1 erase_all

Something is talking to the RfCat dongle (Modem Manager, most likely).
Retrying again after 5 seconds.  This can take a minute, please be
patient.  (error: SerialException(2, "could not open port
/dev/RFCAT_BL_YS1: [Errno 2] No such file or directory:
'/dev/RFCAT_BL_YS1'"))

Something is talking to the RfCat dongle (Modem Manager, most likely).
Retrying again after 5 seconds.  This can take a minute, please be
patient.  (error: SerialException(2, "could not open port
/dev/RFCAT_BL_YS1: [Errno 2] No such file or directory:
'/dev/RFCAT_BL_YS1'"))

Something is talking to the RfCat dongle (Modem Manager, most likely).
Retrying again after 5 seconds.  This can take a minute, please be
patient.  (error: SerialException(2, "could not open port
/dev/RFCAT_BL_YS1: [Errno 2] No such file or directory:
'/dev/RFCAT_BL_YS1'"))

Something is talking to the RfCat dongle (Modem Manager, most likely).
Retrying again after 5 seconds.  This can take a minute, please be
patient.  (error: SerialException(2, "could not open port
/dev/RFCAT_BL_YS1: [Errno 2] No such file or directory:
'/dev/RFCAT_BL_YS1'"))

Something is talking to the RfCat dongle (Modem Manager, most likely).
Retrying again after 5 seconds.  This can take a minute, please be
patient.  (error: SerialException(2, "could not open port
/dev/RFCAT_BL_YS1: [Errno 2] No such file or directory:
'/dev/RFCAT_BL_YS1'"))
^CTraceback (most recent call last):
  File "/home/gray/bin/rfcat_bootloader", line 215, in <module>
    time.sleep(6)
KeyboardInterrupt
Makefile:370: recipe for target 'installRfCatYS1CCBootloader' failed
make: *** [installRfCatYS1CCBootloader] Error 1


gray@gray-VirtualBox:~/rfcat/firmware$ rfcat_bootloader /dev/RFCAT2
erase_all

Something is talking to the RfCat dongle (Modem Manager, most likely).
Retrying again after 5 seconds.  This can take a minute, please be
patient.  (error: SerialException("Could not configure port: (25,
'Inappropriate ioctl for device')",))

Something is talking to the RfCat dongle (Modem Manager, most likely).
Retrying again after 5 seconds.  This can take a minute, please be
patient.  (error: SerialException("Could not configure port: (25,
'Inappropriate ioctl for device')",))
^CTraceback (most recent call last):
  File "/home/gray/bin/rfcat_bootloader", line 215, in <module>
    time.sleep(6)

**Comment by atlas0fd00m** [comment]
gray@gray-VirtualBox:~/rfcat/firmware$ rfcat_bootloader /dev/RFCAT2 erase_all

won't work because RFCAT2 indicates that it's not in Bootloader mode.  you either have to jumper the pins, or use "rfcat --bootloader --force" to kick it into bootloader mode (this is done automatically during the build/install process from the Makefile).

i'm not sure why the install is failing.  
what's the results of:
$ ls -la /dev/RF*

**Comment by trunkafunk** [comment]
gray@gray-VirtualBox:~/rfcat/firmware$ ls -la /dev/RF*
lrwxrwxrwx 1 root root 15 Apr 23 10:00 /dev/RFCAT2 -> bus/usb/002/007

gray@gray-VirtualBox:~/rfcat/firmware$ rfcat --bootloader --force
Entering RfCat Bootloader mode, ready for new image...
Error in resetup():ChipconUsbTimeoutException()

hmmf, I think I messed something up pretty good.. Even jumpering the pins
I'm not getting solid lights. This needs to be done ON insertion yea?

**Comment by atlas0fd00m** [comment]
yes.  @dominicgs @michaelossmann, have any pointers?

@trunkafunk if you have a GoodFET, you may want to try flashing the bootloader and then the new firmware.

$ make installys1bootloader
$ make installRfCatYS1CCBootloader

thanks,
@

**Comment by zhoze** [comment]
How can I use GreatFET instead of GoodFET to flash bootloader and firmware?

**Comment by atlas0fd00m** [comment]
that is a great question, to which i don't currently have the answer.  that's better suited for @dominicgs or @michaelossmann

**Comment by ghost** [comment]
This is a nightmare.

**Comment by atlas0fd00m** [comment]
explain the nightmare?

**Comment by bigoper** [comment]
# HELP
Following the diff tips on this page and [here](https://roaldnefs.com/posts/2019/01/update-yard-stick-one-firmware/) I got the following: 
- not sure how to continue from here
```
$ sudo rfcat_bootloader /dev/cu.usbmodem0000011 download firmware/bins/RfCatYS1CCBootloader.hex          
Writing b':0614000002148B024BFCFC' RC = b'0'(OK)
... TRUNCATED ...
... TRUNCATED ...
Writing b':105A9400EC13FCEB13FBEA13FAE913F9D8F12275C2' RC = b'0'(OK)
Writing b':035AA4008200225B' RC = b'0'(OK)
Skipping non data record: 'b':00000001FF''
```

## USB
- I don't see my device anymore
```
$ ioreg -p IOUSB                                                                                         
+-o Root  <class IORegistryEntry, id 0x100000100, retain 17>
  +-o AppleUSBXHCI Root Hub Simulation@14000000  <class AppleUSBRootHubDevice, id 0x100000329, registered, matched, active, busy 0 (4 ms), retain 16>
    +-o Apple Internal Keyboard / Trackpad@14400000  <class AppleUSBDevice, id 0x100002227, registered, matched, active, busy 0 (1 ms), retain 18>
    +-o BRCM20702 Hub@14300000  <class AppleUSBDevice, id 0x100002255, registered, matched, active, busy 0 (0 ms), retain 12>
      +-o Bluetooth USB Host Controller@14330000  <class AppleUSBDevice, id 0x100002280, registered, matched, active, busy 0 (0 ms), retain 17>
```

# ISSUE RESOLVED
- Link to [source](https://github.com/atlas0fd00m/rfcat/issues/101#issuecomment-775530660):
