### ISSUE TITLE
recipe for target 'RfCatYS1CCBootloader.hex' failed

### ISSUE THREAD

**Issue by SorenAndreasen** [atlas0fd00m/rfcat#53]
When trying to upload newest firmware to my YS1 I do the following:
1. 
pi@raspberrypi:~ $ rfcat --bootloader --force
Entering RfCat Bootloader mode, ready for new image...

2.
CD to the firmware directory

3.
make installRfCatYS1CCBootlader

4. result:
make: *** No rule to make target 'installRfCatYS1CCBootlader'.  Stop.
pi@raspberrypi:~/Downloads/rfcat-master/firmware $ make installRfCatYS1CCBootloader

==RfCatYS1CCBootloader.hex building==
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` --xram-loc 0xF000  --code-loc 0x1400 appFHSSNIC.c chipcon_usb.rel chipcon_usbdebug.rel chipcon_dma.rel bootloader.rel cc1111rf.rel global.rel cc1111_aes.rel -DYARDSTICKONE -DCC1111 -DUSBDEVICE

?ASlink-Warning-Undefined Global '_drawstr_PARM_2' referenced by module 'global'

?ASlink-Warning-Undefined Global '_drawstr_PARM_3' referenced by module 'global'

?ASlink-Warning-Undefined Global '_configureSPI' referenced by module 'global'

?ASlink-Warning-Undefined Global '_setDisplayStart' referenced by module 'global'

?ASlink-Warning-Undefined Global '_setIOPorts' referenced by module 'global'

?ASlink-Warning-Undefined Global '_drawstr' referenced by module 'global'

?ASlink-Warning-Undefined Global '_erasescreen' referenced by module 'global'

?ASlink-Warning-Undefined Global '_setNormalReverse' referenced by module 'global'

?ASlink-Warning-Undefined Global '_LCDReset' referenced by module 'global'
Makefile:98: recipe for target 'RfCatYS1CCBootloader.hex' failed
make: *** [RfCatYS1CCBootloader.hex] Error 1

**Comment by SorenAndreasen** [comment]
I'm wondering if this has to do with that I have gcc also installed. Perhaps it is using gcc instead of sdcc somehow? should i remove gcc completely perhaps ?

**Comment by atlas0fd00m** [comment]
i always have gcc and tons of build-chains installed.  that shouldn't be it.

then again, i don't ever build it on a Pi either.

here's how it goes on my linux laptop:
$ make clean  installRfCatYS1CCBootloader 
                                                                                                                                                                                                                                                                          
==== CLEANING STUFF UP ====                                                                                                                                                                                                                                               
rm -f *.ihx *.rel *.hex *.sym *.asm *.lst *.lnk *.map *.mem *.rst                                                                                                                                                                                                         
#./new_serial.py
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE  -DUSB_DEVICE_SERIAL_NUMBER="`./new_serial.py`" -c chipcon_usb.c
[--- new serial number: 0000 ---]
chipcon_usb.c:681: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:765: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:1302: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
chipcon_usb.c:1302: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c chipcon_usbdebug.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c chipcon_dma.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c bootloader.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c cc1111rf.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c global.c
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DYARDSTICKONE -DCC1111 -DUSBDEVICE -c cc1111_aes.c


==RfCatYS1CCBootloader.hex building==
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` --xram-loc 0xF000  --code-loc 0x1400 appFHSSNIC.c chipcon_usb.rel chipcon_usbdebug.rel chipcon_dma.rel bootloader.rel cc1111rf.rel global.rel cc1111_aes.rel -DYARDSTICKONE -DCC1111 -DUSBDEVICE
packihx <appFHSSNIC.ihx >bins/RfCatYS1CCBootloader.hex
packihx: read 621 lines, wrote 1197: OK.
if [ ! -c /dev/RFCAT_BL_YS1 ] ; then ../rfcat --bootloader --force && sleep 1 ; fi ;
Entering RfCat Bootloader mode, ready for new image...
rfcat_bootloader /dev/RFCAT_BL_YS1 erase_all

**Comment by atlas0fd00m** [comment]
what version of sdcc are you using?

**Comment by SorenAndreasen** [comment]
okay, apparently using "clean" after the make command seemed to work. everything looks updated and fine now! will need to read up on why this command helped. Thank you for your help, very appreciated
