### ISSUE TITLE
confused about rflib  versions

### ISSUE THREAD

**Issue by SorenAndreasen** [atlas0fd00m/rfcat#54]
Hi,

Sorry this isnt really a "bug" as such, but I am trying to implement this 
https://github.com/ComThings/rfcat-rolljam
on 2 yard stick ones with a rasbperry pi. 

Ive come a pretty good stretch of the way, but besides strange USB timeouts once in a while, it seems there are much different versions of this "rflib". Eg, the rflib that the above repository seems to use is one from pandwaRF. Actually, it seems pandwaRF might even have their own version of rfcat as many functions used in this rfcat-rolljam python script i can only find in the pandwaRF repository. Still, the author of rfcat-rolljam says he used 2 yard stick ones and a rpi like i have here.

any tips would be very very appreciated.
btw, im not onto any shady business here. trying to make a prototype for my company

**Comment by atlas0fd00m** [comment]
hey @SorenAndreasen , i appreciate the work you're doing. 
i'm not sure how old the pandwaRF version of rflib is.  are you running into problems?  rflib versions represent the python code.  what's the problem you're running into?  perhaps i can help answer them.

@
