### ISSUE TITLE
Control location of python install

### ISSUE THREAD

**Issue by wagnerat** [atlas0fd00m/rfcat#55]
Firstly, this isn't quite an _issue_, per se.

I'm working on installing rfcat on a raspberry pi. The pi & project I'm working with are using berryconda, and as such I'd love to be able to point the install towards the python located within the berryconda directory (/home/pi/berryconda/lib). I've been poring through the files cloned from this repo to look for where in the install process the python path might be called/determined, but so far I'm coming up empty. As such, I figured I'd drop by here and see if anyone is able to offer help. 

Thanks!

**Comment by atlas0fd00m** [comment]
just insert /home/pi/berryconda/lib in your PYTHONPATH environment variable.  if that doesn't solve the problem, please explain a bit more of the constraints you're trying to overcome.

@
