### ISSUE TITLE
Snap packaging (contribution)?

### ISSUE THREAD

**Issue by phocean** [atlas0fd00m/rfcat#56]
Hello,

I packaged rfcat as a snap:
https://snapcraft.io/rfcat-phocean
https://github.com/phocean/rfcat-snapcraft

If you are interested, I would be happy to contribute it and help maintaining it (in an official snap).
Let me know if you are interested.

And thank you for your work :-)

**Comment by atlas0fd00m** [comment]
thank you, @phocean .  
email me at atlas@r4780y.com and let's discuss what that would look like.
