### ISSUE TITLE
Question about Yardstick One

### ISSUE THREAD

**Issue by Videogamer555** [atlas0fd00m/rfcat#57]
I hear Yardstick One uses this firmware. So what I want to know is this. How do I actually control Yardstick One (or any other device that uses this firmware)? Do I need to use Zadig to install WinUSB or LibUSB to install the proper driver (and then download or write my own software designed to control the device via this driver)? Or is the device automatically recognized (without any manual driver installation) by Windows as a serial port device, so I can use normal terminal software to control it?

**Comment by grvvy** [comment]
Yardstick One ships with rfcat installed on it. You can control the device from an ipython shell, an example of Yardstick One being used (on Linux), as well as a great reverse engineering demonstration can be found [here](https://www.youtube.com/watch?v=8kIxlMIGctc). Installation instructions can be found [here](https://github.com/atlas0fd00m/rfcat#installing-with-bootloader).
