### ISSUE TITLE
Yardstick One amplifier not working

### ISSUE THREAD

**Issue by nobody656** [atlas0fd00m/rfcat#59]
Hello,how can i enable Yardstick One power amplifiers....when i use d.setMaxPower() it just set power of cc1111...and when i set d.setAmpMode(1) i dont see any change in signal power...thanks for help

**Comment by atlas0fd00m** [comment]
the power amps are enabled by default in the YS1 firmware.  as you indicated, d.setMaxPower() only configures in the CC1111 hardware.  can you force different output levels between d.setAmpMode(x) where x changes?

if you cannot identify a difference, perhaps @dominicgs and @michaelossmann can shed some light.  mike wrote the firmware/client changes for the amplifiers.

@

**Comment by pickeditmate** [comment]
Sorry for the massive necro but this ticket is still open, I've just tested the latest rfcat release (on windows 10 x64, python 3.9) and it seems that setting d.setAmp(n) does in fact work, where n=0 or any even number the amp is off, where n=1 or any odd number the amp is on and evident in the SDR waterfall.

**Comment by atlas0fd00m** [comment]
thank you for the follow-up @pickeditmate .  @nobody656 , were you still having any issues?
i believe what you may have been seeing is the fact that the power amp is automatically enabled on the YS1.
