### ISSUE TITLE
CC1111 Disconnect Issue.

### ISSUE THREAD

**Issue by tj-oconnor** [atlas0fd00m/rfcat#60]
Helo, 

New RFCat user. I flashed RFcat on my CC1111DK Rev 1.3 dongle using a GoodFet. It seemed to work fine. Its connected to a Kali virtual machine through a USB-A to USB-C hub. I open rfcat -r and can print my config using print(d.reprRadioConfig()). 

```
>>> print(d.reprRadioConfig())
== Hardware ==
Dongle:              DONSDONGLE
Firmware rev:        0543
Compiler:            SDCCv380
Bootloader:          Not installed

== Software ==
rflib rev:           543
```

However, once I attempt to set the frequency or perform any configuration changes, it resets. 

```
>>> d.setModeIDLE()
>>> d.setFreq(433000000)
===== RESETUP set from recv thread
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)
```

In dmesg, I can see where it just disconnects. Any advice on why this happening or what I'm doing wrong? Thanks.

```
[  552.601600] usb 2-2.2: new full-speed USB device number 8 using uhci_hcd
[  552.707906] usb 2-2.2: not running at top speed; connect to a high speed hub
[  552.719859] usb 2-2.2: New USB device found, idVendor=1d50, idProduct=6048, bcdDevice= 1.01
[  552.719862] usb 2-2.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  552.719864] usb 2-2.2: Product: Dons Dongle
[  552.719865] usb 2-2.2: Manufacturer: RfCat
[  552.719867] usb 2-2.2: SerialNumber: 0000
---> After trying to d.setFreq(
[  690.503640] usb 2-2.2: USB disconnect, device number 8
```

.tj

**Comment by 7doctor7** [comment]
The same issue I have.

**Comment by atlas0fd00m** [comment]
@tj-oconnor @7doctor7 
was this issue ever resolved?  closing this for now, but please reopen if it's still an issue
