### ISSUE TITLE
d.setEnablePktAppendStatus() not working

### ISSUE THREAD

**Issue by daviddlpg** [atlas0fd00m/rfcat#61]
Hello everybody,

I am trying to test my 433Mhz garage remote, and i would like to study the RSSI and LQI coverage. I have a Yard Stick One configured with my signal parameters and i receive the keyfob and the garage transceiver frames correctly.

I have set up the d.setEnablePktAppendStatus() parameter in the rfcat interpreter and is enabled, as i can see when i run print(d.reprRadioConfig()), but the LQI and RSSI dont appears in the frames as the two last bytes together with the checksum byte.

I have tested another parameters and i compiled the last firmware again in the YT1 without success:

== Hardware ==
Dongle:              YARDSTICKONE
Firmware rev:        0543
Compiler:            SDCCv350
Bootloader:          CC-Bootloader

I also have been reading the CC1111 manual so as to be sure that the register that d.setEnablePktAppendStatus() writes is correct (PKCTRL1), but i haven't found a solution. 

May be it could be a bug?. 

Please help¡ Thanks in advance...

**Comment by atlas0fd00m** [comment]
i'm not sure we plumbed LQI and RSSI through the entire message chain.  because the capabilities of the CC1111 were pretty amazing and because LQI/RSSI didn't seem like a vital part of the capabilities to wrap in.  i don't think it would take much to wrap it in.  are you interested in writing a little code?  it would teach you RfCat comms like nothing else will :)

**Comment by chrisVat** [comment]
Is there a quick way to retrieve RSSI values without reflashing the Ys1?

**Comment by atlas0fd00m** [comment]
currently the only way to grab RSSI is to use d.getRSSI().
@daviddlpg is this still of interest to you?

blanket apology for long delay, somehow GitHub stopped sending me notifications.
