### ISSUE TITLE
RFCAT and SDR dongles

### ISSUE THREAD

**Issue by fe77** [atlas0fd00m/rfcat#62]
Hi Guys,
Are there any plan to support SDR (I have a RTL SDR V3) ?
Thanks
Best regards.

**Comment by atlas0fd00m** [comment]
sorry, no.  

SDR uses exceptionally different hardware, and the variances in quality/parameters of SDR are vast.  to support SDR would require a huge rewrite.  RfCat was created to leverage the power of the CC1111 MCU/Radio/USB system-on-chip.  

SDRcat would be an excellent project to write, however!  

might i suggest URH, Inspectrum, and GnuRadio-Companion?
