### ISSUE TITLE
please HELP

### ISSUE THREAD

**Issue by sparta3355** [atlas0fd00m/rfcat#68]
In [1]: print(d.reprRadioConfig())
== Hardware ==
Dongle:              YARDSTICKONE
Firmware rev:        0348
Compiler:            Not found! Update needed!
Bootloader:          CC-Bootloader

and

/rfcat/firmware# make installys1bootloader
./bootloader_serial.py 
[--- new serial number: 0004 ---]
goodfet.cc erase
Traceback (most recent call last):
  File "/usr/local/bin/goodfet.cc", line 153, in <module>
    client.serInit()
  File "/root/goodfet/client/GoodFET.py", line 133, in serInit
    self.pyserInit(port,timeout,attemptlimit);
  File "/root/goodfet/client/GoodFET.py", line 142, in pyserInit
    import serial;
ImportError: No module named serial
make: *** [Makefile:536: installys1bootloader] Error 1

**Comment by atlas0fd00m** [comment]
you need the serial module for python installed. that varies by your os, but on ubuntu, try:

apt install python-serial

**Comment by PlantDaddy** [comment]
Or on pypi, it's pyserial. The normal pypi 'serial' package is for serializing JSON objects.

$ pip3 install pyserial  #python3

**Comment by atlas0fd00m** [comment]
thanks @PlantDaddy .

**Comment by meeas** [comment]
@atlas0fd00m I've been meaning to tell you we needed to add pyserial to setup.py.  Sorry I forgot until just now.
