### ISSUE TITLE
Excuse me, is there an Android version of rfcat?

### ISSUE THREAD

**Issue by leon-uhs** [atlas0fd00m/rfcat#69]

**Comment by meeas** [comment]
Nope, there is not.  You might be able to get it working in a rooted Android via Python, but I'm not sure how the Yardstick would show up as Android doesn't support most USB devices out of the box.

**Comment by atlas0fd00m** [comment]
sorry, no plans as of yet.  too many other things on the docket.  very open to pull requests and instructions, however!
