### ISSUE TITLE
please tag a proper version

### ISSUE THREAD

**Issue by blshkv** [atlas0fd00m/rfcat#77]
There  is a big confusion about the current version. Every distro calls it differently currently:
https://repology.org/project/rfcat/versions

Please come up with your versioning format and tag a release properly.

**Comment by ZeroChaos-** [comment]
last version best version https://github.com/atlas0fd00m/rfcat/releases/tag/InfiniteMode_works_fine_at_this_point._Merging_slowly_because_first_attempts_didn't_turn_out_so_well_

**Comment by blshkv** [comment]
FYI
https://en.wikipedia.org/wiki/Software_versioning
https://semver.org/

so a tag like "MAJOR.MINOR.PATCH" would do  it perfectly

**Comment by atlas0fd00m** [comment]
thank you both.  this makes sense to me.  it seems i need to put on my big-boy pants and tag versions.  my apologies for waiting so long.

**Comment by ZeroChaos-** [comment]
our love will be eternal if you tag a real version after merging python3 support. :-D

**Comment by atlas0fd00m** [comment]
lol.  i'll make the py3 cut-over be version v2.0.0.  today i cut v1.0.0 just for you ;)  working on py3 stuff.  i heard that Kali has a Py3 port, but it's apparently broken.

**Comment by atlas0fd00m** [comment]
@ZeroChaos- @blshkv - get your eternal love ready.  oh, and test this out.

https://github.com/atlas0fd00m/rfcat/releases/tag/v1.9.1

**Comment by mnhauke** [comment]
Thanks a lot for the prerelease.
I have just prepared a version bump for the openSUSE package.

Here are some minor issues with v1.9.1:

* setup.py
  * uses version 1.0.1 instead of 1.9.1
  * uses python_requires  = '>=2.7,<3.0.0'  (seems wrong since we now claim python3 support)

* rfcat_msfrelay
  * is not converted to python3 yet...
```
$ /usr/bin/rfcat_msfrelay
Traceback (most recent call last):
  File "/usr/bin/rfcat_msfrelay", line 16, in <module>
    from BaseHTTPServer import BaseHTTPRequestHandler,HTTPServer
ModuleNotFoundError: No module named 'BaseHTTPServer'

```

**Comment by blshkv** [comment]
I'm also getting:

```
Writing /var/tmp/portage/net-wireless/rfcat-1.9.1/image/_python3.7/usr/lib/python3.7/site-packages/rfcat-1.0.1-py3.7.egg-info
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    file('rflib/rflib_version.py', 'wb').write("RFLIB_VERSION=%s" % REV)
NameError: name 'file' is not defined
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
 * Using python3.7 in global scope

```

**Comment by blshkv** [comment]
https://github.com/repology/repology-rules/issues/407#event-3709931043

**Comment by atlas0fd00m** [comment]
it's going to take me a little bit to get the nuance down of releasing and PyPi sync.  i've not done this before.  i need to make a release and then push to PyPi.  

@mnhauke you're right, i missed rfcat_msfrelay!  sorry.
@blshkv i believe that's fixed in the latest subrelease (and the latest in PyPi).

**Comment by atlas0fd00m** [comment]
hey all, 
RfCat v1.9.2 has been released on github (https://github.com/atlas0fd00m/rfcat/releases/tag/v1.9.2  as well as on  PyPi.    

please look through and find bugs :)

choose one or all of the following 
1) pip install -U rfcat      
2) download the release from github and install/use it      
3) git clone/pull to update to the latest version

we're trying to make sure all the code is Python3 ready, so BREAK IT and help us be confident that all the nooks and crannies are working well.  bug reports are good.  Pull Requests (PR) on github are better.  PR's with unit tests for some part of the code are even better still!  if you have any questions about any of these options, reach out to me here or at my personal email address <atlas@<redacted_check_your_email_notifications>>  unittests are pretty easy to make, PR's are pretty easy to make.  but both are a lot easier after your first time, and i'm happy to help there too.

**Comment by atlas0fd00m** [comment]
closing for now.  releasing 1.9.3 right now.  please find bugs, file fixes (PRs) and issues :)

**Comment by blshkv** [comment]
Great, thanks!
