### ISSUE TITLE
Bang for my buck?

### ISSUE THREAD

**Issue by cyb3rr0nn13** [atlas0fd00m/rfcat#85]
i know, this isnt the right place for this issue, 
but i think the most likely one to get an answer......

my issue is, that i cant use my yard stick one, cuz rfcat wont let me....
i thought it comes preinstalled, but not on my stick.....
and it seems like im too stupid to compile my own one on my Pi4B

Heres the log
`not-root@p15dr:~ $ lsusb
Bus 002 Device 003: ID 0bda:8153 Realtek Semiconductor Corp. RTL8153 Gigabit Ethernet Adapter
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 021: ID 1d50:605b OpenMoko, Inc. RfCat YARD Stick One
Bus 001 Device 010: ID 04d9:0006 Holtek Semiconductor, Inc. 
Bus 001 Device 008: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 017: ID 047d:2048 Kensington Orbit Trackball with Scroll Ring
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
not-root@p15dr:~ $ dmesg
[184065.841753] usb 1-1.4.3: new full-speed USB device number 21 using xhci_hcd
[184065.983645] usb 1-1.4.3: New USB device found, idVendor=1d50, idProduct=605b, bcdDevice= 1.00
[184065.983654] usb 1-1.4.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[184065.983660] usb 1-1.4.3: Product: YARD Stick One
[184065.983667] usb 1-1.4.3: SerialNumber: 0093
`

Hope somebody could help me out.....
Thanks folks

UPDATE:

ive cloned the rfcat repo and tried to open....what i got is this

`not-root@p15dr:/usr/share/rfcat $ sudo ./rfcat 

===== RESETUP set from recv thread
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.')
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.')
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.')
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.')
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.')
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.')
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.')`

BTW, the fucking dongle is connected as if it were from viacom....
i also tried to open the rfcat file with python2, but also a fucking deadend
log below

`not-root@p15dr:/usr/share/rfcat $ sudo python2 ./rfcat
I���"J&���e�����m���~�ņ��"A�

��Q�  ��HSod�7�
               l���by�4ӎx��|��29�������,$�z�GĈ%�{�������t8�yt�Ã%�婲�Vod���̱x���;q'a�|���
                                                                                       ��;�˓M��������X\=3�m�~"��!ܫ�-����yV7� ����c��NЍ����<��	²��ҥ�I���<{�I5NN1�2�	Tq!�'�SBA
`

**Comment by cyb3rr0nn13** [comment]
ok, im a step further now.....
anybody knows how to install pyside2 on a Pi4B?
log is as always below 

`not-root@p15dr:/usr/share/rfcat $ sudo python setup.py install
running install
running bdist_egg
running egg_info
creating rfcat.egg-info
writing requirements to rfcat.egg-info/requires.txt
writing rfcat.egg-info/PKG-INFO
writing top-level names to rfcat.egg-info/top_level.txt
writing dependency_links to rfcat.egg-info/dependency_links.txt
writing manifest file 'rfcat.egg-info/SOURCES.txt'
reading manifest file 'rfcat.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'rfcat.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build
creating build/lib.linux-armv7l-2.7
creating build/lib.linux-armv7l-2.7/tests
copying tests/__init__.py -> build/lib.linux-armv7l-2.7/tests
copying tests/test_api.py -> build/lib.linux-armv7l-2.7/tests
copying tests/test_basics.py -> build/lib.linux-armv7l-2.7/tests
creating build/lib.linux-armv7l-2.7/rflib
copying rflib/ccspecan.py -> build/lib.linux-armv7l-2.7/rflib
copying rflib/__init__.py -> build/lib.linux-armv7l-2.7/rflib
copying rflib/chipcon_nic.py -> build/lib.linux-armv7l-2.7/rflib
copying rflib/rflib_version.py -> build/lib.linux-armv7l-2.7/rflib
copying rflib/fakedongle_nic.py -> build/lib.linux-armv7l-2.7/rflib
copying rflib/ccrecvdump.py -> build/lib.linux-armv7l-2.7/rflib
copying rflib/chipcon_usb.py -> build/lib.linux-armv7l-2.7/rflib
copying rflib/rflib_defs.py -> build/lib.linux-armv7l-2.7/rflib
copying rflib/cc111Xhparser.py -> build/lib.linux-armv7l-2.7/rflib
copying rflib/const.py -> build/lib.linux-armv7l-2.7/rflib
copying rflib/bits.py -> build/lib.linux-armv7l-2.7/rflib
copying rflib/chipcondefs.py -> build/lib.linux-armv7l-2.7/rflib
copying rflib/intelhex.py -> build/lib.linux-armv7l-2.7/rflib
creating build/lib.linux-armv7l-2.7/rflib/vstruct
copying rflib/vstruct/__init__.py -> build/lib.linux-armv7l-2.7/rflib/vstruct
copying rflib/vstruct/builder.py -> build/lib.linux-armv7l-2.7/rflib/vstruct
copying rflib/vstruct/primitives.py -> build/lib.linux-armv7l-2.7/rflib/vstruct
creating build/bdist.linux-armv7l
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/tests
copying build/lib.linux-armv7l-2.7/tests/__init__.py -> build/bdist.linux-armv7l/egg/tests
copying build/lib.linux-armv7l-2.7/tests/test_api.py -> build/bdist.linux-armv7l/egg/tests
copying build/lib.linux-armv7l-2.7/tests/test_basics.py -> build/bdist.linux-armv7l/egg/tests
creating build/bdist.linux-armv7l/egg/rflib
copying build/lib.linux-armv7l-2.7/rflib/ccspecan.py -> build/bdist.linux-armv7l/egg/rflib
copying build/lib.linux-armv7l-2.7/rflib/__init__.py -> build/bdist.linux-armv7l/egg/rflib
copying build/lib.linux-armv7l-2.7/rflib/chipcon_nic.py -> build/bdist.linux-armv7l/egg/rflib
copying build/lib.linux-armv7l-2.7/rflib/rflib_version.py -> build/bdist.linux-armv7l/egg/rflib
copying build/lib.linux-armv7l-2.7/rflib/fakedongle_nic.py -> build/bdist.linux-armv7l/egg/rflib
copying build/lib.linux-armv7l-2.7/rflib/ccrecvdump.py -> build/bdist.linux-armv7l/egg/rflib
copying build/lib.linux-armv7l-2.7/rflib/chipcon_usb.py -> build/bdist.linux-armv7l/egg/rflib
copying build/lib.linux-armv7l-2.7/rflib/rflib_defs.py -> build/bdist.linux-armv7l/egg/rflib
copying build/lib.linux-armv7l-2.7/rflib/cc111Xhparser.py -> build/bdist.linux-armv7l/egg/rflib
copying build/lib.linux-armv7l-2.7/rflib/const.py -> build/bdist.linux-armv7l/egg/rflib
creating build/bdist.linux-armv7l/egg/rflib/vstruct
copying build/lib.linux-armv7l-2.7/rflib/vstruct/__init__.py -> build/bdist.linux-armv7l/egg/rflib/vstruct
copying build/lib.linux-armv7l-2.7/rflib/vstruct/builder.py -> build/bdist.linux-armv7l/egg/rflib/vstruct
copying build/lib.linux-armv7l-2.7/rflib/vstruct/primitives.py -> build/bdist.linux-armv7l/egg/rflib/vstruct
copying build/lib.linux-armv7l-2.7/rflib/bits.py -> build/bdist.linux-armv7l/egg/rflib
copying build/lib.linux-armv7l-2.7/rflib/chipcondefs.py -> build/bdist.linux-armv7l/egg/rflib
copying build/lib.linux-armv7l-2.7/rflib/intelhex.py -> build/bdist.linux-armv7l/egg/rflib
byte-compiling build/bdist.linux-armv7l/egg/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/tests/test_api.py to test_api.pyc
byte-compiling build/bdist.linux-armv7l/egg/tests/test_basics.py to test_basics.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/ccspecan.py to ccspecan.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/chipcon_nic.py to chipcon_nic.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/rflib_version.py to rflib_version.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/fakedongle_nic.py to fakedongle_nic.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/ccrecvdump.py to ccrecvdump.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/chipcon_usb.py to chipcon_usb.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/rflib_defs.py to rflib_defs.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/cc111Xhparser.py to cc111Xhparser.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/const.py to const.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/vstruct/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/vstruct/builder.py to builder.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/vstruct/primitives.py to primitives.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/bits.py to bits.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/chipcondefs.py to chipcondefs.pyc
byte-compiling build/bdist.linux-armv7l/egg/rflib/intelhex.py to intelhex.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
installing scripts to build/bdist.linux-armv7l/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
copying and adjusting rfcat -> build/scripts-2.7
copying and adjusting rfcat_server -> build/scripts-2.7
copying and adjusting rfcat_msfrelay -> build/scripts-2.7
copying and adjusting CC-Bootloader/rfcat_bootloader -> build/scripts-2.7
changing mode of build/scripts-2.7/rfcat from 644 to 755
changing mode of build/scripts-2.7/rfcat_server from 644 to 755
changing mode of build/scripts-2.7/rfcat_msfrelay from 644 to 755
changing mode of build/scripts-2.7/rfcat_bootloader from 644 to 755
creating build/bdist.linux-armv7l/egg/EGG-INFO/scripts
copying build/scripts-2.7/rfcat -> build/bdist.linux-armv7l/egg/EGG-INFO/scripts
copying build/scripts-2.7/rfcat_bootloader -> build/bdist.linux-armv7l/egg/EGG-INFO/scripts
copying build/scripts-2.7/rfcat_server -> build/bdist.linux-armv7l/egg/EGG-INFO/scripts
copying build/scripts-2.7/rfcat_msfrelay -> build/bdist.linux-armv7l/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-armv7l/egg/EGG-INFO/scripts/rfcat to 755
changing mode of build/bdist.linux-armv7l/egg/EGG-INFO/scripts/rfcat_bootloader to 755
changing mode of build/bdist.linux-armv7l/egg/EGG-INFO/scripts/rfcat_server to 755
changing mode of build/bdist.linux-armv7l/egg/EGG-INFO/scripts/rfcat_msfrelay to 755
copying rfcat.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying rfcat.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying rfcat.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying rfcat.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying rfcat.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/rfcat-1.9.3-py2.7.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing rfcat-1.9.3-py2.7.egg
Copying rfcat-1.9.3-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Removing rfcat 1.9.2 from easy-install.pth file
Adding rfcat 1.9.3 to easy-install.pth file
Installing rfcat script to /usr/local/bin
Installing rfcat_server script to /usr/local/bin
Installing rfcat_bootloader script to /usr/local/bin
Installing rfcat_msfrelay script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/rfcat-1.9.3-py2.7.egg
Processing dependencies for rfcat==1.9.3
Searching for PySide2
Reading https://pypi.org/simple/PySide2/
No local packages or working download links found for PySide2
error: Could not find suitable distribution for Requirement.parse('PySide2')
`

EDIT: im deep down in the rabbithole right now....
https://www.codice-sorgente.it/raspbian-buster-pyside2-lxqt/#English

**Comment by cyb3rr0nn13** [comment]
Forget all the shit above......i figured it out now.....

1. Uninstall rfcat
2. Clone rfcat
3. Navigate into cloned folder
4. sudo ./rfcat -r
5. Were done!
6. Close this issue

Peace out, mothersuckers! Until next time :)

**Comment by atlas0fd00m** [comment]
if you put the `etc/udev/rules.d/20-rfcat.rules`  into your `/etc/udev/rules.d/` directory, you don't need `sudo`
