### ISSUE TITLE
d.RFxmit("test") returns an TypeError: can't concat str to bytes 

### ISSUE THREAD

**Issue by OrangeFran** [atlas0fd00m/rfcat#86]
I started to play with this yesterday and noticed this error. After looking at the line `1127` in `chipcon_nic.py` I found out that python3 fails to concat `struct.pack(...)` and `data` because the first returns a bytes like object and the second one is a string. This error probably comes from python2 where `struct.pack` returns a string, that got changed in python3 according to the documentation.

Fixing this should be pretty easy, just change `b"%s" % struct.pack("<HHH",len(data),repeat,offset)+data` to `struct.pack("<HHH",len(data),repeat,offset)+data.encode("utf-8")`. Please correct me if I'm wrong. I hope I'm right with `utf-8`. I don't know for sure which encoding is used.

**Comment by OrangeFran** [comment]
One could also use `d.RFxmit(b"test")` without errors for now but then the part `b"%s" %` could just be left out. But since the documentation says `d.RFxmit` should be used with a string I suggest fixing this so that the function accepts strings.

**Comment by atlas0fd00m** [comment]
please hand in a bytes object `b'sdfasdf'` instead.  did you get it worked out?
