### ISSUE TITLE
PySide2 not available for install.

### ISSUE THREAD

**Issue by maaxxyy** [atlas0fd00m/rfcat#89]
Hi guys is there a work around due to PySide2 not available anymore. I cant get rfcat installed due to this.
This is what i get when trying to run rfcat -

pi@raspberrypi:~/rfcat $ rfcat -r
Traceback (most recent call last):
  File "/usr/local/bin/rfcat", line 4, in <module>
    __import__('pkg_resources').run_script('rfcat==1.9.3', 'rfcat')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PySide2' distribution was not found and is required by rfcat
---------------------------------------------------------------------------------
Right i downloaded the updated version of rfcat v 1.0.0 and now i'm getting this issue - 

pi@raspberrypi:~/rfcat-1.0.0 $ rfcat -r
'RfCat, the greatest thing since Frequency Hopping!'

Research Mode: enjoy the raw power of rflib

currently your environment has an object called "d" for dongle.  this is how 
you interact with the rfcat dongle:
    >>> d.ping()
    >>> d.setFreq(433000000)
    >>> d.setMdmModulation(MOD_ASK_OOK)
    >>> d.makePktFLEN(250)
    >>> d.RFxmit("HALLO")
    >>> d.RFrecv()
    >>> print(d.reprRadioConfig())

In [1]:

**Comment by maaxxyy** [comment]
At the end of the interactive shell i have 'In [1]' in green, sorry about the font size on the last post. 
Now when i run d.specan(433920000) i get another error related to PySide2????

**Comment by oosfoos** [comment]
see here for more woes about pyside2 on raspberry pi:
https://forum.qt.io/topic/103466/how-can-i-install-pysde2-in-raspberry-pi

**Comment by oosfoos** [comment]
good news...  rfcat only uses  pyside2 for the ccspecan stuff. (not that important imho)

Meaning you can either:

1. Remove pyside2 from requirements.txt (and proceed not to use ccspecan )

or

2. Try to just downgrade to pyside1 by reverting these changes here https://github.com/roaldnefs/rfcat/commit/2c60bdcd8a567dbffc21d5803a480590676767be

**Comment by atlas0fd00m** [comment]
try now.

**Comment by atlas0fd00m** [comment]
just did.  let me know what you think.
