### ISSUE TITLE
Yard Stick One firmware update error

### ISSUE THREAD

**Issue by AdimadLp** [atlas0fd00m/rfcat#94]
== Hardware ==
Dongle:              b'YARDSTICKONE'
Firmware rev:        b'0348\x00'
Compiler:            Not found! Update needed!
Bootloader:          CC-Bootloader

== Software ==
rflib rev:           598

I tried to update the firmware with using the 'make installRfCatYS1CCBootloader' command, but then i have got this error.

TypeError: unicode strings are not supported, please encode to bytes: ':00000023DD\n'
make: *** [Makefile:378: installRfCatYS1CCBootloader] error 1

thanks for help

**Comment by brederm** [comment]
> 
> 
> == Hardware ==
> Dongle: b'YARDSTICKONE'
> Firmware rev: b'0348\x00'
> Compiler: Not found! Update needed!
> Bootloader: CC-Bootloader
> 
> == Software ==
> rflib rev: 598
> 
> I tried to update the firmware with using the 'make installRfCatYS1CCBootloader' command, but then i have got this error.
> 
> TypeError: unicode strings are not supported, please encode to bytes: ':00000023DD\n'
> make: *** [Makefile:378: installRfCatYS1CCBootloader] error 1
> 
> thanks for help

Same issue here!

**Comment by oosfoos** [comment]
having the same problem here...
looks to be the same issue as #88

guessing it's a python3 thing :/

______
I got it to work, but i tried so many thing i am really not sure what ultimately did it.

in the end i was using python2.7 as root, i'll try to be more help if someone else can't jump in here and just fix it.

**Comment by atlas0fd00m** [comment]
thanks guys.  
i've not finished migrating the CC-Bootloader code to use Python3.  my apologies.  it should currently still work with python2.  until this is complete, rfcat_bootloader should be changed to use "python2" instead of "python" in case python2 is not default.
my apologies for the delay.  i've been having trouble getting my lab equipment and myself to all work at the same time.  PR's welcome ;)  anyone care to migrate rfcat_bootloader to py3?

@

**Comment by atlas0fd00m** [comment]
i just pushed a new version of rfcat_bootloader, which should work on py3.  currently the "verify" process is taking a very long time, but it seems to work.  i'm not sure why.  it works fast under python2.

**Comment by atlas0fd00m** [comment]
@oosfoos @brederm  @AdimadLp could you please check this out and let me know how it goes for you?

**Comment by AdimadLp** [comment]
Thanks, i think that worked. But now i get a new error, when i use RFxmit. TypeError: can't concat str to bytes
And btw how can i use GQRX with my YS1. I cant see it in the Listbox

**Comment by Loumiakas** [comment]
Hi @atlas0fd00m, I've tried firmware update using Python3 and it seems to be working well, though I did experience slower verification on my system as well.

```
== Hardware ==
Dongle:              b'YARDSTICKONE'
Firmware rev:        b'0604\x00'
Compiler:            b'SDCCv350\x00'
Bootloader:          CC-Bootloader

== Software ==
rflib rev:           604
```

**Comment by atlas0fd00m** [comment]
@AdimadLp great!  glad to hear it.

two things:
1) please include the top output from "d.printClientConfig()" like @Loumiakas just did.
2) sadly, GQRX uses a software-defined radio (SDR).  RfCat uses a hardware radio.  as much as i would love to join their functionality, they are incompatible.

merry Christmas and happy new year!
@

**Comment by atlas0fd00m** [comment]
> Hi @atlas0fd00m, I've tried firmware update using Python3 and it seems to be working well, though I did experience slower verification on my system as well.
> 
> ```
> == Hardware ==
> Dongle:              b'YARDSTICKONE'
> Firmware rev:        b'0604\x00'
> Compiler:            b'SDCCv350\x00'
> Bootloader:          CC-Bootloader
> 
> == Software ==
> rflib rev:           604
> ```

thanks @Loumiakas !
i'm unclear what the delay is at this point.  hopefully it'll become clear soon.  right now i'm "fixing up the troops" (ie. getting my existing RfCats all up to snuff and working again).

**Comment by Loumiakas** [comment]
Hey @AdimadLp, I could be wrong, but unlike with Python2, Python3 byte literals should always be prefixed with 'b' e.g. ```d.RFxmit(b'1234')```, otherwise byte string will be treated as str type, causing issue described by your post. Could you try explicitly converting your message to byte string and see if it works?

**Comment by atlas0fd00m** [comment]
just pushed updates to pypi.  check out the latest version: https://pypi.org/project/rfcat/1.9.4/
upgrade with

$ pip install -U rfcat

**Comment by AdimadLp** [comment]
Thanks to you all.
Now everything works perfectly.
== Hardware ==
Dongle:              b'YARDSTICKONE'
Firmware rev:        b'0604\x00'
Compiler:            b'SDCCv350\x00'
Bootloader:          CC-Bootloader

== Software ==
rflib rev:           609

@Loumiakas that was my problem.

Happy new year :-)
