### ISSUE TITLE
RFcat

### ISSUE THREAD

**Issue by hack-gif** [atlas0fd00m/rfcat#96]
I'm trying to download RFcat,  I'm following the steps from "Hak5", I did it in the past not long ago and it worked just fine. Right now when trying to wget, it says that is not found, also I looked in the web and it says that "that link has no power here".

**Comment by Loumiakas** [comment]
Would you mind sharing link that you are trying to follow instructions from? My guess is that setup guide is quite outdated, so it will not work anymore. In any case, the easiest and most straight forward way to install rfcat is through python package installaer (pip): ```pip3 install rfcat```

**Comment by hack-gif** [comment]
"https://www.hak5.org/episodes/hak5-1908-how-to-begin-hacking-with-the-yard-stick-one" 
" wget https://bitbucket.org/atlas0fd00m/rfcat/downloads/rfcat_150225.tgz"
I would try it to install through python

**Comment by Loumiakas** [comment]
That article is really outdated. Author moved rfcat repository from Bitbucket to Github since. I recommend that you perform installation through pip, in order to avoid issues.

**Comment by hack-gif** [comment]
I did download rfcat, but how i would progress now, I mean is not like explained in that site, I guess is different. any site with explanation from A to B?

**Comment by Loumiakas** [comment]
Once you have installed rfcat though pip, you can still follow steps on that website; But you would need to start from where ```sudo rfcat -r``` command is mentioned, as steps before that are not needed anymore.

**Comment by hack-gif** [comment]
I cant sudo rfcat -r , it says that command not found "rfcat"

**Comment by oosfoos** [comment]
try doing a `sudo pip3 install rfcat`
or run
`sudo cp etc/udev/rules.d/20-rfcat.rules /etc/udev/rules.d
sudo udevadm control --reload-rules`

and try again

**Comment by Loumiakas** [comment]
> 
> 
> I cant sudo rfcat -r , it says that command not found "rfcat"

Ok, in that case, you could try running ```rfcat -r```, as pip most likely installed it locally. If you get errors related to permissions, I would recommend that you reinstall rfcat with superuser privileges:

```pip3 uninstall rfcat # removes local instance of rfcat```
```sudo pip3 install rfcat # install global instance of rfcat```

**Comment by atlas0fd00m** [comment]
yeah, installing it as the user places scripts into `~/.local/bin`, which is often not in the actual path.
