### ISSUE TITLE
YS1 update firmware error

### ISSUE THREAD

**Issue by DroidKali** [atlas0fd00m/rfcat#99]
```bash
rfcat --bootloader --force
```
```bash
rfcat_bootloader /dev/ttyACM0 download RfCatYS1-201231.hex
.......
Writing b':105A450020F71430F6148883A88220F507E6A8838A' RC = b'0'(OK)
Writing b':105A550075830022E280F7E49322E0226040F82576' RC = b'0'(OK)
Writing b':105A650082500274FFF582E824F8501ECCCBCAF9A7' RC = b'0'(OK)
Writing b':105A7500E4CC24F85014CBCAF9E4CB24F8500BCA73' RC = b'0'(OK)
Writing b':105A8500F9E4CA24F8500379002224086010F8C309' RC = b'0'(OK)
Writing b':105A9500EC13FCEB13FBEA13FAE913F9D8F12275C1' RC = b'0'(OK)
Writing b':035AA5008200225A' RC = b'0'(OK)
Skipping non data record: 'b':00000001FF''
```
Can't update firmware

**Comment by Loumiakas** [comment]
/Are you sure it failed to update? What is the output of _Firmware Rev_  when issuing ```print(d.reprRadioConfig())``` command? It should be close to the last commit number i.e.  >605 <=612, if you are using relatively new version of rfcat.

**Comment by DroidKali** [comment]
OK,finally i have succeed to upgrade to YS1 firmware,and i want to know can this works on Windows env？

**Comment by Loumiakas** [comment]
I could be wrong, but I would say no. There are rfcat dependent python libraries like 'readline' that are only utilized by UNIX systems. Also, access to the device is fundamentally different on Windows, so I don't think that part was implemented in rfcat either.

**Comment by DroidKali** [comment]
Ok, thank you anyway

**Comment by ghost** [comment]
I got the same thing as @DroidKali

rfcat_bootloader /dev/ttyACM0 download bins/RfCatYS1CCBootloader.hex
.......
Writing b':0259EE0058F669' RC = b'0'(OK)
Writing b':0D148B00758157125A4FE5826003021486E6' RC = b'0'(OK)
Writing b':1059F00020F71430F6148883A88220F507E6A883E0' RC = b'0'(OK)
Writing b':105A000075830022E280F7E49322E0226040F825CB' RC = b'0'(OK)
Writing b':105A100082500274FFF582E824F8501ECCCBCAF9FC' RC = b'0'(OK)
Writing b':105A2000E4CC24F85014CBCAF9E4CB24F8500BCAC8' RC = b'0'(OK)
Writing b':105A3000F9E4CA24F8500379002224086010F8C35E' RC = b'0'(OK)
Writing b':105A4000EC13FCEB13FBEA13FAE913F9D8F1227516' RC = b'0'(OK)
Writing b':035A5000820022AF' RC = b'0'(OK)
Skipping non data record: 'b':00000001FF''

After unplugging/replugging the YSOne, I got a fixed green light, and not recognized on my linux laptop.
I get no dmesg output when I plug it.

**Comment by pickeditmate** [comment]
I'm fairly sure fixed green light on the yardstick means it's in bootloader mode. Do you happen to have a means to flash the .hex directly with a goodfet or a greatfet? I've just done mine as amazon shipped an older version which didn't like windows, the new version is working fine on Windows 10 when issuing python rfcat -r (I only have python v3 installed by the way)
